#!/usr/bin/env python3
"""Validate a GENERATED_ARCHITECTURE.md file against the canonical template."""

import re
import sys
from pathlib import Path


REQUIRED_H2_SECTIONS = [
    "Metadata",
    "Purpose",
    "Architecture Components",
    "APIs Exposed",
    "Dependencies",
    "Network Architecture",
    "Security",
    "Data Flows",
    "Integration Points",
    "Recent Changes",
    "Source References",
]

REQUIRED_H3_SUBSECTIONS = {
    "APIs Exposed": [
        "Custom Resource Definitions (CRDs)",
        "HTTP Endpoints",
        "gRPC Services",
    ],
    "Dependencies": [
        "External Dependencies",
        "Internal Platform Dependencies",
    ],
    "Network Architecture": [
        "Services",
        "Ingress",
        "Egress",
    ],
    "Security": [
        "RBAC - Cluster Roles",
        "RBAC - Role Bindings",
        "Secrets",
        "Authentication & Authorization",
    ],
    "Source References": [
        "Files Analyzed",
        "Grep/Search Results Used",
        "Summary",
    ],
}

REQUIRED_METADATA_FIELDS = [
    "Repository",
    "Version",
    "Distribution",
    "Languages",
    "Deployment Type",
    "Generated By",
]

EXPECTED_TABLE_HEADERS = {
    "Architecture Components": ["Component", "Type", "Purpose"],
    "Custom Resource Definitions (CRDs)": ["Group", "Version", "Kind", "Scope", "Purpose"],
    "HTTP Endpoints": ["Path", "Method", "Port", "Protocol", "Encryption", "Auth", "Purpose"],
    "gRPC Services": ["Service", "Port", "Protocol", "Encryption", "Auth", "Purpose"],
    "External Dependencies": ["Component", "Version", "Required", "Purpose"],
    "Internal Platform Dependencies": ["Component", "Interaction Type", "Purpose"],
    "Services": ["Service Name", "Type", "Port", "Target Port", "Protocol", "Encryption", "Auth", "Exposure"],
    "Ingress": ["Name", "Type", "Hosts", "Port", "Protocol", "Encryption", "TLS Mode", "Exposure"],
    "Egress": ["Destination", "Port", "Protocol", "Encryption", "Auth", "Purpose"],
    "RBAC - Cluster Roles": ["Role Name", "API Group", "Resources", "Verbs"],
    "RBAC - Role Bindings": ["Binding Name", "Namespace", "Role", "Service Account"],
    "Secrets": ["Secret Name", "Type", "Purpose", "Provisioned By", "Auto-Rotate"],
    "Authentication & Authorization": ["Endpoint", "Methods", "Auth Mechanism", "Enforcement Point", "Policy"],
    "Integration Points": ["Component", "Interaction Type", "Port", "Protocol", "Encryption", "Purpose"],
    "Recent Changes": ["Version", "Date", "Changes"],
    "Files Analyzed": ["File", "Lines", "Sections Informed"],
    "Grep/Search Results Used": ["Search Pattern", "Files Matched", "Sections Informed"],
}


def _parse_headings(text: str) -> list[tuple[int, str]]:
    """Extract (level, title) for all markdown headings."""
    headings = []
    for line in text.splitlines():
        m = re.match(r'^(#{1,6})\s+(.+)$', line)
        if m:
            headings.append((len(m.group(1)), m.group(2).strip()))
    return headings


def _parse_tables(text: str) -> dict[str, list[str]]:
    """Map section heading -> table column headers found under it.

    Returns only the first table found under each heading.
    """
    tables: dict[str, list[str]] = {}
    current_section = None

    for line in text.splitlines():
        m = re.match(r'^(#{2,3})\s+(.+)$', line)
        if m:
            current_section = m.group(2).strip()
            # Strip "Flow N:" prefix for data flows
            current_section = re.sub(r'^Flow \d+:\s*', '', current_section)
            continue

        if current_section and current_section not in tables:
            if line.strip().startswith('|') and '---' not in line:
                cols = [c.strip() for c in line.strip().strip('|').split('|')]
                cols = [c for c in cols if c]
                if cols:
                    tables[current_section] = cols

    return tables


def _parse_metadata_fields(text: str) -> list[str]:
    """Extract metadata field names from the Metadata section."""
    fields = []
    in_metadata = False
    for line in text.splitlines():
        if re.match(r'^##\s+Metadata\s*$', line):
            in_metadata = True
            continue
        if in_metadata and re.match(r'^##\s+', line):
            break
        if in_metadata:
            m = re.match(r'^-\s+\*\*(.+?)\*\*:', line)
            if m:
                fields.append(m.group(1))
    return fields


def validate(path: str) -> tuple[list[str], list[str]]:
    """Return (errors, warnings). Errors are blocking, warnings are informational."""
    errors = []
    warnings = []
    filepath = Path(path)

    if not filepath.exists():
        return [f"File not found: {path}"], []

    text = filepath.read_text()

    if not text.strip():
        return ["File is empty"], []

    headings = _parse_headings(text)

    # --- H1 check ---
    h1s = [title for level, title in headings if level == 1]
    if not h1s:
        errors.append("Missing H1 heading (expected '# Component: [Name]')")
    elif not h1s[0].startswith("Component:"):
        warnings.append(f"H1 should start with 'Component:' (got '# {h1s[0]}')")

    # --- H2 section presence and order ---
    h2s = [title for level, title in headings if level == 2]
    found_required = [s for s in h2s if s in REQUIRED_H2_SECTIONS]
    missing_h2 = [s for s in REQUIRED_H2_SECTIONS if s not in h2s]

    for section in missing_h2:
        errors.append(f"Missing required section: ## {section}")

    # Check order of found sections
    expected_order = [s for s in REQUIRED_H2_SECTIONS if s in found_required]
    if found_required != expected_order:
        errors.append(
            f"Sections out of order. Expected: {expected_order}, "
            f"got: {found_required}"
        )

    # Warn on extra H2 sections
    extra_h2 = [s for s in h2s if s not in REQUIRED_H2_SECTIONS]
    for section in extra_h2:
        warnings.append(f"Unexpected section: ## {section} (not in template)")

    # --- H3 subsections ---
    h3_by_parent: dict[str, list[str]] = {}
    current_h2 = None
    for level, title in headings:
        if level == 2:
            current_h2 = title
        elif level == 3 and current_h2:
            h3_by_parent.setdefault(current_h2, []).append(title)

    for h2, required_h3s in REQUIRED_H3_SUBSECTIONS.items():
        if h2 in missing_h2:
            continue
        actual_h3s = h3_by_parent.get(h2, [])
        for h3 in required_h3s:
            if h3 not in actual_h3s:
                errors.append(f"Missing subsection: ### {h3} (under ## {h2})")

    # --- Metadata fields ---
    if "Metadata" not in missing_h2:
        meta_fields = _parse_metadata_fields(text)
        for field in REQUIRED_METADATA_FIELDS:
            if field not in meta_fields:
                errors.append(f"Missing metadata field: **{field}**")

    # --- Table column headers ---
    tables = _parse_tables(text)
    for section_name, expected_cols in EXPECTED_TABLE_HEADERS.items():
        if section_name in tables:
            actual_cols = tables[section_name]
            if actual_cols != expected_cols:
                warnings.append(
                    f"Table columns mismatch in '{section_name}': "
                    f"expected {expected_cols}, got {actual_cols}"
                )

    return errors, warnings


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <GENERATED_ARCHITECTURE.md>")
        sys.exit(2)

    errors, warnings = validate(sys.argv[1])

    if warnings:
        print(f"WARNINGS ({len(warnings)}):\n")
        for w in warnings:
            print(f"  ~ {w}")
        print()

    if errors:
        print(f"VALIDATION FAILED - {len(errors)} error(s):\n")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)
    else:
        print("VALIDATION PASSED")
        sys.exit(0)


if __name__ == "__main__":
    main()
