package renderer

import (
	"fmt"
	"io"
	"strings"

	"github.com/jctanner/arch-analyzer/internal/model"
)

func Markdown(writer io.Writer, document model.Document) error {
	for _, row := range document.CRDs {
		if strings.TrimSpace(row.Group) == "" || strings.TrimSpace(row.Version) == "" ||
			strings.TrimSpace(row.Kind) == "" || strings.TrimSpace(row.Scope) == "" {
			return fmt.Errorf("render CRD row with incomplete identity: group=%q version=%q kind=%q scope=%q",
				row.Group, row.Version, row.Kind, row.Scope)
		}
	}
	markdown := &markdownWriter{writer: writer}
	markdown.line("# Component: %s", document.Component)
	markdown.blank()

	markdown.heading(2, "Metadata")
	markdown.line("- **Repository**: %s", cell(document.Metadata.Repository))
	markdown.line("- **Version**: %s", cell(document.Metadata.Version))
	markdown.line("- **Distribution**: %s", cell(document.Metadata.Distribution))
	markdown.line("- **Languages**: %s", cell(document.Metadata.Languages))
	markdown.line("- **Deployment Type**: %s", cell(document.Metadata.DeploymentType))
	markdown.line("- **Generated By**: %s", cell(document.Metadata.GeneratedBy))
	markdown.blank()

	renderProvenance(markdown, document)

	markdown.heading(2, "Purpose")
	markdown.line("**Short**: %s", deterministicShortPurpose(document))
	markdown.blank()
	markdown.line("**Detailed**: %s", deterministicDetailedPurpose(document))
	markdown.blank()

	renderArchitecturalAnalysis(markdown, document)

	renderContract(markdown, document.Contract)

	markdown.heading(2, "Architecture Components")
	markdown.table(
		[]string{"Component", "Type", "Purpose"},
		mapRows(document.ArchitectureComponents, func(row model.ArchitectureComponent) []string {
			return []string{row.Component, row.Type, row.Purpose}
		}),
	)

	markdown.heading(2, "APIs Exposed")
	markdown.heading(3, "Custom Resource Definitions (CRDs)")
	renderCRDCountScope(markdown, document.CRDs)
	markdown.table(
		[]string{"Group", "Version", "Kind", "Scope", "API Role", "Purpose"},
		mapRows(document.CRDs, func(row model.CRDRow) []string {
			return []string{row.Group, row.Version, row.Kind, row.Scope, row.APIRole, row.Purpose}
		}),
	)
	markdown.heading(3, "Serving Runtime Definitions")
	markdown.table(
		[]string{"Name", "Kind", "API Group", "Version", "Scope", "Supported Model Formats", "Container Images", "Built-in Adapter", "Source"},
		mapRows(document.ServingRuntimes, func(row model.ServingRuntimeRow) []string {
			return []string{row.Name, row.Kind, row.APIGroup, row.Version, row.Scope, row.SupportedModelFormats, row.ContainerImages, row.BuiltInAdapter, row.Source}
		}),
	)
	markdown.heading(3, "HTTP Endpoints")
	markdown.table(
		[]string{"Path", "Method", "Port", "Protocol", "Transport", "Encryption", "Auth", "Owner", "Purpose"},
		mapRows(document.HTTPEndpoints, func(row model.HTTPEndpointRow) []string {
			return []string{row.Path, row.Method, row.Port, row.Protocol, row.Transport, row.Encryption, row.Auth, row.Owner, row.Purpose}
		}),
	)
	markdown.heading(3, "gRPC Services")
	markdown.table(
		[]string{"Service", "Port", "Protocol", "Transport", "Encryption", "Auth", "Owner", "Purpose"},
		mapRows(document.GRPCServices, func(row model.GRPCServiceRow) []string {
			return []string{row.Service, row.Port, row.Protocol, row.Transport, row.Encryption, row.Auth, row.Owner, row.Purpose}
		}),
	)

	markdown.heading(2, "Dependencies")
	markdown.heading(3, "External Dependencies")
	markdown.table(
		[]string{"Component", "Version", "Required", "Role", "Purpose"},
		mapRows(document.ExternalDependencies, func(row model.ExternalDependencyRow) []string {
			return []string{row.Component, row.Version, row.Required, row.Role, row.Purpose}
		}),
	)
	markdown.heading(3, "Internal Platform Dependencies")
	markdown.table(
		[]string{"Component", "Interaction Type", "Role", "Purpose"},
		mapRows(document.InternalDependencies, func(row model.InternalDependencyRow) []string {
			return []string{row.Component, row.InteractionType, row.Role, row.Purpose}
		}),
	)

	markdown.heading(2, "Network Architecture")
	markdown.heading(3, "Services")
	markdown.table(
		[]string{"Service Name", "Type", "Port", "Target Port", "Protocol", "Encryption", "Auth", "Exposure"},
		mapRows(document.Services, func(row model.ServiceRow) []string {
			return []string{row.Name, row.Type, row.Port, row.TargetPort, row.Protocol, row.Encryption, row.Auth, row.Exposure}
		}),
	)
	markdown.heading(3, "Ingress")
	markdown.table(
		[]string{"Name", "Type", "Hosts", "Port", "Protocol", "Encryption", "TLS Mode", "Exposure"},
		mapRows(document.Ingress, func(row model.IngressRow) []string {
			return []string{row.Name, row.Type, row.Hosts, row.Port, row.Protocol, row.Encryption, row.TLSMode, row.Exposure}
		}),
	)
	markdown.heading(3, "Egress")
	markdown.table(
		[]string{"Destination", "Port", "Protocol", "Encryption", "Auth", "Purpose"},
		mapRows(document.Egress, func(row model.EgressRow) []string {
			return []string{row.Destination, row.Port, row.Protocol, row.Encryption, row.Auth, row.Purpose}
		}),
	)

	markdown.heading(2, "Security")
	markdown.heading(3, "RBAC - Cluster Roles")
	markdown.table(
		[]string{"Role Name", "API Group", "Resources", "Verbs"},
		mapRows(document.ClusterRoles, func(row model.ClusterRoleRow) []string {
			return []string{row.Name, row.APIGroup, row.Resources, row.Verbs}
		}),
	)
	markdown.heading(3, "RBAC - Role Bindings")
	markdown.table(
		[]string{"Binding Name", "Namespace", "Role", "Service Account"},
		mapRows(document.RoleBindings, func(row model.RoleBindingRow) []string {
			return []string{row.Name, row.Namespace, row.Role, row.ServiceAccount}
		}),
	)
	markdown.heading(3, "Secrets")
	markdown.table(
		[]string{"Secret Name", "Type", "Purpose", "Provisioned By", "Auto-Rotate"},
		mapRows(document.Secrets, func(row model.SecretRow) []string {
			return []string{row.Name, row.Type, row.Purpose, row.ProvisionedBy, row.AutoRotate}
		}),
	)
	markdown.heading(3, "Authentication & Authorization")
	markdown.table(
		[]string{"Endpoint", "Methods", "Auth Mechanism", "Enforcement Point", "Policy"},
		mapRows(document.Authentication, func(row model.AuthenticationRow) []string {
			return []string{row.Endpoint, row.Methods, row.Mechanism, row.EnforcementPoint, row.Policy}
		}),
	)
	markdown.heading(3, "Security Evidence")
	markdown.table(
		[]string{"Kind", "Target", "Detail", "Signal Type"},
		mapRows(document.SecurityEvidence, func(row model.SecurityEvidence) []string {
			return []string{row.Kind, row.Target, row.Detail, row.Status}
		}),
	)

	if len(document.Webhooks) > 0 {
		markdown.heading(2, "Admission Webhooks")
		markdown.table(
			[]string{"Name", "Type", "Path", "Port", "Failure Policy", "Resources", "Operations", "Purpose"},
			mapRows(document.Webhooks, func(row model.WebhookRow) []string {
				return []string{row.Name, row.Type, row.Path, row.Port, row.FailurePolicy, row.Resources, row.Operations, row.Purpose}
			}),
		)
	}

	markdown.heading(2, "Data Flows")
	for _, flow := range deterministicDataFlows(document) {
		markdown.line("- %s", flow)
	}
	markdown.blank()

	markdown.heading(2, "Integration Points")
	for _, point := range deterministicIntegrationPoints(document) {
		markdown.line("- %s", point)
	}
	markdown.blank()
	markdown.table(
		[]string{"Component", "Interaction Type", "Role", "Port", "Protocol", "Encryption", "Purpose"},
		mapRows(document.IntegrationPoints, func(row model.IntegrationPointRow) []string {
			return []string{row.Component, row.InteractionType, row.Role, row.Port, row.Protocol, row.Encryption, row.Purpose}
		}),
	)

	markdown.heading(2, "Recent Changes")
	markdown.table(
		[]string{"Version", "Date", "Changes"},
		mapRows(document.RecentChanges, func(row model.RecentChange) []string {
			return []string{row.Version, row.Date, row.Changes}
		}),
	)

	return markdown.err
}

func renderCRDCountScope(markdown *markdownWriter, rows []model.CRDRow) {
	if len(rows) == 0 {
		return
	}
	counts := map[string]int{}
	for _, row := range rows {
		role := strings.TrimSpace(row.APIRole)
		if role == "" {
			role = "Unknown"
		}
		counts[role]++
	}
	markdown.line(
		"CRD count scope: %d core API CRDs; %d total CRD/API rows including configuration and visibility APIs.",
		counts["Core API"],
		len(rows),
	)
	markdown.blank()
}

func renderProvenance(markdown *markdownWriter, document model.Document) {
	if len(document.RepoLineage) == 0 {
		return
	}
	markdown.heading(2, "Provenance")
	markdown.heading(3, "Repo Lineage")
	markdown.table(
		[]string{"Role", "Repository", "Sync Mechanism", "Sync Branch", "Sync Workflows", "Detection Method"},
		mapRows(document.RepoLineage, func(row model.RepoLineageRow) []string {
			return []string{row.Role, row.Repository, row.SyncMechanism, row.SyncBranch, row.SyncWorkflows, row.DetectionMethod}
		}),
	)
	markdown.heading(3, "Aliases")
	markdown.table(
		[]string{"Current Name", "Previous Name", "Type", "Context"},
		nil,
	)
}

func renderArchitecturalAnalysis(markdown *markdownWriter, document model.Document) {
	markdown.heading(2, "Architectural Analysis")
	markdown.line("Pending analyzer-assisted synthesis. Rewrite this section into concise architecture narrative using the analyzer facts, synthesis context, and any bounded source evidence. Do not retain analyzer coverage diagnostics or deterministic inventory bullets in the final Markdown.")
	markdown.blank()
}

type markdownWriter struct {
	writer io.Writer
	err    error
}

func (markdown *markdownWriter) line(format string, args ...any) {
	if markdown.err != nil {
		return
	}
	_, markdown.err = fmt.Fprintf(markdown.writer, format+"\n", args...)
}

func (markdown *markdownWriter) blank() {
	markdown.line("")
}

func (markdown *markdownWriter) heading(level int, title string) {
	markdown.line("%s %s", strings.Repeat("#", level), title)
	markdown.blank()
}

func (markdown *markdownWriter) table(headers []string, rows [][]string) {
	markdown.line("| %s |", strings.Join(headers, " | "))
	separator := make([]string, len(headers))
	for index := range separator {
		separator[index] = strings.Repeat("-", max(3, len(headers[index])))
	}
	markdown.line("|%s|", strings.Join(separator, "|"))
	for _, row := range rows {
		values := make([]string, len(headers))
		for index := range values {
			if index < len(row) {
				values[index] = cell(row[index])
			}
		}
		markdown.line("| %s |", strings.Join(values, " | "))
	}
	markdown.blank()
}

func cell(value string) string {
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.TrimSpace(value)
}

func mapRows[T any](items []T, mapper func(T) []string) [][]string {
	rows := make([][]string, 0, len(items))
	for _, item := range items {
		rows = append(rows, mapper(item))
	}
	return rows
}
