package renderer

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/jctanner/arch-analyzer/internal/model"
)

func Markdown(writer io.Writer, document model.Document) error {
	for _, row := range document.CRDs {
		if strings.TrimSpace(row.Group) == "" || strings.TrimSpace(row.Version) == "" ||
			strings.TrimSpace(row.Kind) == "" || strings.TrimSpace(row.Scope) == "" {
			return fmt.Errorf("render CRD row with incomplete identity: group=%q version=%q kind=%q scope=%q",
				row.Group, row.Version, row.Kind, row.Scope)
		}
	}
	markdown := &markdownWriter{writer: writer}
	markdown.line("# Component: %s", document.Component)
	markdown.blank()

	markdown.heading(2, "Metadata")
	markdown.line("- **Repository**: %s", cell(document.Metadata.Repository))
	markdown.line("- **Version**: %s", cell(document.Metadata.Version))
	markdown.line("- **Distribution**: %s", cell(document.Metadata.Distribution))
	markdown.line("- **Languages**: %s", cell(document.Metadata.Languages))
	markdown.line("- **Deployment Type**: %s", cell(document.Metadata.DeploymentType))
	markdown.line("- **Generated By**: %s", cell(document.Metadata.GeneratedBy))
	markdown.blank()

	renderContract(markdown, document.Contract)

	markdown.heading(2, "Purpose")
	markdown.line("**Short**: %s", deterministicShortPurpose(document))
	markdown.blank()
	markdown.line("**Detailed**: %s", deterministicDetailedPurpose(document))
	markdown.blank()

	markdown.heading(2, "Architecture Components")
	markdown.table(
		[]string{"Component", "Type", "Purpose"},
		mapRows(document.ArchitectureComponents, func(row model.ArchitectureComponent) []string {
			return []string{row.Component, row.Type, row.Purpose}
		}),
	)

	markdown.heading(2, "APIs Exposed")
	markdown.heading(3, "Custom Resource Definitions (CRDs)")
	markdown.table(
		[]string{"Group", "Version", "Kind", "Scope", "Purpose"},
		mapRows(document.CRDs, func(row model.CRDRow) []string {
			return []string{row.Group, row.Version, row.Kind, row.Scope, row.Purpose}
		}),
	)
	markdown.heading(3, "HTTP Endpoints")
	markdown.table(
		[]string{"Path", "Method", "Port", "Protocol", "Transport", "Encryption", "Auth", "Owner", "Purpose"},
		mapRows(document.HTTPEndpoints, func(row model.HTTPEndpointRow) []string {
			return []string{row.Path, row.Method, row.Port, row.Protocol, row.Transport, row.Encryption, row.Auth, row.Owner, row.Purpose}
		}),
	)
	markdown.heading(3, "gRPC Services")
	markdown.table(
		[]string{"Service", "Port", "Protocol", "Transport", "Encryption", "Auth", "Owner", "Purpose"},
		mapRows(document.GRPCServices, func(row model.GRPCServiceRow) []string {
			return []string{row.Service, row.Port, row.Protocol, row.Transport, row.Encryption, row.Auth, row.Owner, row.Purpose}
		}),
	)

	markdown.heading(2, "Dependencies")
	markdown.heading(3, "External Dependencies")
	markdown.table(
		[]string{"Component", "Version", "Required", "Role", "Purpose"},
		mapRows(document.ExternalDependencies, func(row model.ExternalDependencyRow) []string {
			return []string{row.Component, row.Version, row.Required, row.Role, row.Purpose}
		}),
	)
	markdown.heading(3, "Internal Platform Dependencies")
	markdown.table(
		[]string{"Component", "Interaction Type", "Role", "Purpose"},
		mapRows(document.InternalDependencies, func(row model.InternalDependencyRow) []string {
			return []string{row.Component, row.InteractionType, row.Role, row.Purpose}
		}),
	)

	markdown.heading(2, "Network Architecture")
	markdown.heading(3, "Services")
	markdown.table(
		[]string{"Service Name", "Type", "Port", "Target Port", "Protocol", "Encryption", "Auth", "Exposure"},
		mapRows(document.Services, func(row model.ServiceRow) []string {
			return []string{row.Name, row.Type, row.Port, row.TargetPort, row.Protocol, row.Encryption, row.Auth, row.Exposure}
		}),
	)
	markdown.heading(3, "Ingress")
	markdown.table(
		[]string{"Name", "Type", "Hosts", "Port", "Protocol", "Encryption", "TLS Mode", "Exposure"},
		mapRows(document.Ingress, func(row model.IngressRow) []string {
			return []string{row.Name, row.Type, row.Hosts, row.Port, row.Protocol, row.Encryption, row.TLSMode, row.Exposure}
		}),
	)
	markdown.heading(3, "Egress")
	markdown.table(
		[]string{"Destination", "Port", "Protocol", "Encryption", "Auth", "Purpose"},
		mapRows(document.Egress, func(row model.EgressRow) []string {
			return []string{row.Destination, row.Port, row.Protocol, row.Encryption, row.Auth, row.Purpose}
		}),
	)

	markdown.heading(2, "Security")
	markdown.heading(3, "RBAC - Cluster Roles")
	markdown.table(
		[]string{"Role Name", "API Group", "Resources", "Verbs"},
		mapRows(document.ClusterRoles, func(row model.ClusterRoleRow) []string {
			return []string{row.Name, row.APIGroup, row.Resources, row.Verbs}
		}),
	)
	markdown.heading(3, "RBAC - Role Bindings")
	markdown.table(
		[]string{"Binding Name", "Namespace", "Role", "Service Account"},
		mapRows(document.RoleBindings, func(row model.RoleBindingRow) []string {
			return []string{row.Name, row.Namespace, row.Role, row.ServiceAccount}
		}),
	)
	markdown.heading(3, "Secrets")
	markdown.table(
		[]string{"Secret Name", "Type", "Purpose", "Provisioned By", "Auto-Rotate"},
		mapRows(document.Secrets, func(row model.SecretRow) []string {
			return []string{row.Name, row.Type, row.Purpose, row.ProvisionedBy, row.AutoRotate}
		}),
	)
	markdown.heading(3, "Authentication & Authorization")
	markdown.table(
		[]string{"Endpoint", "Methods", "Auth Mechanism", "Enforcement Point", "Policy"},
		mapRows(document.Authentication, func(row model.AuthenticationRow) []string {
			return []string{row.Endpoint, row.Methods, row.Mechanism, row.EnforcementPoint, row.Policy}
		}),
	)
	markdown.heading(3, "Security Evidence")
	markdown.table(
		[]string{"Kind", "Target", "Detail", "Status"},
		mapRows(document.SecurityEvidence, func(row model.SecurityEvidence) []string {
			return []string{row.Kind, row.Target, row.Detail, row.Status}
		}),
	)

	if len(document.Webhooks) > 0 {
		markdown.heading(2, "Admission Webhooks")
		markdown.table(
			[]string{"Name", "Type", "Path", "Port", "Failure Policy", "Resources", "Operations", "Purpose"},
			mapRows(document.Webhooks, func(row model.WebhookRow) []string {
				return []string{row.Name, row.Type, row.Path, row.Port, row.FailurePolicy, row.Resources, row.Operations, row.Purpose}
			}),
		)
	}

	markdown.heading(2, "Data Flows")
	for _, flow := range deterministicDataFlows(document) {
		markdown.line("- %s", flow)
	}
	markdown.blank()

	markdown.heading(2, "Integration Points")
	for _, point := range deterministicIntegrationPoints(document) {
		markdown.line("- %s", point)
	}
	markdown.blank()
	markdown.table(
		[]string{"Component", "Interaction Type", "Role", "Port", "Protocol", "Encryption", "Purpose"},
		mapRows(document.IntegrationPoints, func(row model.IntegrationPointRow) []string {
			return []string{row.Component, row.InteractionType, row.Role, row.Port, row.Protocol, row.Encryption, row.Purpose}
		}),
	)

	markdown.heading(2, "Architectural Analysis")
	for _, finding := range deterministicArchitecturalAnalysis(document) {
		markdown.line("- %s", finding)
	}
	markdown.blank()

	markdown.heading(2, "Recent Changes")
	markdown.table(
		[]string{"Version", "Date", "Changes"},
		mapRows(document.RecentChanges, func(row model.RecentChange) []string {
			return []string{row.Version, row.Date, row.Changes}
		}),
	)

	markdown.heading(2, "Source References")
	markdown.heading(3, "Files Analyzed")
	markdown.table(
		[]string{"File", "Lines", "Sections Informed"},
		mapRows(document.Sources, func(row model.SourceRow) []string {
			return []string{row.File, row.Lines, row.Sections}
		}),
	)
	markdown.heading(3, "Grep/Search Results Used")
	markdown.table([]string{"Search Pattern", "Files Matched", "Sections Informed"}, nil)
	markdown.heading(3, "Summary")
	markdown.line("- **Total files referenced**: %d", len(document.Sources))
	markdown.line("- **Coverage**: Structured facts and deterministic synthesis are derived from analyzer evidence; partial coverage is stated explicitly.")
	coverageKeys := make([]string, 0, len(document.DataCoverage))
	for key := range document.DataCoverage {
		coverageKeys = append(coverageKeys, key)
	}
	sort.Strings(coverageKeys)
	for _, key := range coverageKeys {
		markdown.line("- **Analyzer coverage (%s)**: %s", key, document.DataCoverage[key])
	}
	categoryKeys := make([]string, 0, len(document.CategoryCoverage))
	for key := range document.CategoryCoverage {
		categoryKeys = append(categoryKeys, key)
	}
	sort.Strings(categoryKeys)
	for _, key := range categoryKeys {
		coverage := document.CategoryCoverage[key]
		detail := fmt.Sprintf("%s under %s; %d facts", coverage.Status, coverage.DiscoveryContract, coverage.FactCount)
		if len(coverage.CompletedChecks) > 0 {
			detail += "; checks: " + strings.Join(coverage.CompletedChecks, ", ")
		}
		if len(coverage.Limitations) > 0 {
			detail += "; limitations: " + strings.Join(coverage.Limitations, "; ")
		}
		markdown.line("- **Category coverage (%s)**: %s", key, detail)
	}
	markdown.blank()

	return markdown.err
}

type markdownWriter struct {
	writer io.Writer
	err    error
}

func (markdown *markdownWriter) line(format string, args ...any) {
	if markdown.err != nil {
		return
	}
	_, markdown.err = fmt.Fprintf(markdown.writer, format+"\n", args...)
}

func (markdown *markdownWriter) blank() {
	markdown.line("")
}

func (markdown *markdownWriter) heading(level int, title string) {
	markdown.line("%s %s", strings.Repeat("#", level), title)
	markdown.blank()
}

func (markdown *markdownWriter) table(headers []string, rows [][]string) {
	markdown.line("| %s |", strings.Join(headers, " | "))
	separator := make([]string, len(headers))
	for index := range separator {
		separator[index] = strings.Repeat("-", max(3, len(headers[index])))
	}
	markdown.line("|%s|", strings.Join(separator, "|"))
	for _, row := range rows {
		values := make([]string, len(headers))
		for index := range values {
			if index < len(row) {
				values[index] = cell(row[index])
			}
		}
		markdown.line("| %s |", strings.Join(values, " | "))
	}
	markdown.blank()
}

func cell(value string) string {
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.TrimSpace(value)
}

func mapRows[T any](items []T, mapper func(T) []string) [][]string {
	rows := make([][]string, 0, len(items))
	for _, item := range items {
		rows = append(rows, mapper(item))
	}
	return rows
}
