import json
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from lib.phases import architecture  # noqa: E402


def _valid_insight_artifact_json(component: str = "example") -> str:
    return json.dumps(
        {
            "schema_version": 1,
            "component": component,
            "platform": "rhoai",
            "version": "rhoai.next",
            "insights": [
                {
                    "id": "test-001",
                    "claim": "Test pattern.",
                    "category": "pattern",
                    "provenance": [
                        {
                            "kind": "analyzer-fact",
                            "location": "Architecture Components table",
                        }
                    ],
                    "reasoning": "Test reasoning.",
                    "applicability": "component",
                    "confidence": "high",
                    "validation_status": "pending",
                }
            ],
        }
    )


def _empty_insight_artifact_json(component: str = "example") -> str:
    return json.dumps(
        {
            "schema_version": 1,
            "component": component,
            "platform": "rhoai",
            "version": "rhoai.next",
            "insights": [],
        }
    )


def architecture_document(component_type: str, purpose: str) -> str:
    return f"""# Component: Example

## Metadata
- **Repository**: example/example
- **Version**: abc123
- **Distribution**: rhoai
- **Languages**: Python
- **Deployment Type**: Service
- **Generated By**: Test Model

## Purpose
{purpose}

## Architecture Components
| Component | Type | Purpose |
|-----------|------|---------|
| api | {component_type} | API |

## Data Flows
Agent data flow.

## Architectural Analysis
Agent analysis.
"""


def analyzer_only_document() -> str:
    return architecture_document("Service", "Analyzer purpose.") + """
## Dependencies

### Internal Platform Dependencies

| Component | Interaction Type | Purpose |
|-----------|------------------|---------|
| platform-api | HTTP client | Platform integration |

## Security

### Authentication & Authorization

| Endpoint | Methods | Auth Mechanism | Enforcement Point | Policy |
|----------|---------|----------------|-------------------|--------|
| /api | GET | Bearer token | middleware | authenticated |

## Integration Points

| Component | Interaction Type | Port | Protocol | Encryption | Purpose |
|-----------|------------------|------|----------|------------|---------|
| database | SQL client | 5432 | PostgreSQL | TLS | persistence |
"""


def write_analyzer_artifacts(
    architecture_dir: Path,
    platform: str,
    component: str,
    markdown: str,
    *,
    readiness: str = "sufficient",
    analyzer_component: str | None = None,
) -> Path:
    analyzer_root = architecture.analyzer_output_dir(
        architecture_dir, platform, component
    )
    analyzer_root.mkdir(parents=True, exist_ok=True)
    (analyzer_root / "analyzer_architecture.md").write_text(markdown)
    (analyzer_root / "component-architecture.json").write_text(
        json.dumps(
            {
                "component": analyzer_component or component,
                "data_coverage": {
                    "agent_baseline": f"{readiness}: test analyzer facts",
                },
            }
        )
    )
    return analyzer_root


@pytest.mark.asyncio
async def test_generation_opt_in_archives_merges_reports_and_validates(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Agent purpose.")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", analyzer)
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        output_path = Path(jobs[0]["output_path"])
        assert output_path.read_text() == analyzer
        output_path.write_text(candidate)
        Path(jobs[0]["insight_path"]).write_text(_empty_insight_artifact_json())
        return [
            {
                "name": "example",
                "success": True,
                "duration_seconds": 1,
                "telemetry": {
                    "duration_api_ms": 850,
                    "source_read_operations": 2,
                    "denied_tool_calls": 1,
                    "tool_calls_by_activity": {
                        "analyzer_context_read": 3,
                        "architecture_output_edit": 1,
                        "sidecar_write": 2,
                        "targeted_discovery": 1,
                    },
                    "denied_tool_calls_by_category": {
                        "workflow-noise": 1,
                    },
                },
            }
        ]

    validation_calls = []

    def fake_validate(command, **kwargs):
        validation_calls.append(command)
        return SimpleNamespace(returncode=0, stdout="VALIDATION PASSED", stderr="")

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(architecture.subprocess, "run", fake_validate)

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert "--change-output=" in captured_jobs[0]["prompt"]
    assert "--insights-output=" in captured_jobs[0]["prompt"]
    assert "--platform=rhoai" in captured_jobs[0]["prompt"]
    assert "--version=rhoai.next" in captured_jobs[0]["prompt"]
    assert "--readiness=sufficient" in captured_jobs[0]["prompt"]
    assert "--baseline-preseeded" in captured_jobs[0]["prompt"]
    assert captured_jobs[0]["agent_policy"]["route"] == "partial"
    output_path = architecture.component_output_path(tmp_path, "rhoai.next", "example")
    assert (
        "| api | Service | API |"
        in output_path.read_text()
    )
    assert "Agent purpose." in output_path.read_text()
    assert "| api | Library | API |" in (log_dir / "example.candidate.md").read_text()
    report = json.loads((log_dir / "example.merge.json").read_text())
    assert report["counts"]["restored"] == 1
    assert (log_dir / "example.merge.md").is_file()
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["routing"]["readiness"] == "sufficient"
    assert run_report["merge"]["counts"]["restored"] == 1
    assert run_report["insights"]["insight_count"] == 0
    assert run_report["insights"]["artifact_path"] == str(
        log_dir / "example.insights.json"
    )
    assert run_report["runtime_breakdown"]["agent_api_seconds"] == 0.85
    assert run_report["runtime_breakdown"]["agent_activity_counts"] == {
        "analyzer_context_reads": 3,
        "targeted_source_reads": 2,
        "targeted_discovery_calls": 1,
        "architecture_output_edits": 1,
        "sidecar_writes": 2,
        "denied_calls": 1,
    }
    assert run_report["runtime_breakdown"]["denied_calls_by_category"] == {
        "workflow-noise": 1,
    }
    assert (
        run_report["runtime_breakdown"]["orchestrator_seconds"][
            "merged_document_validation"
        ]
        is not None
    )
    assert run_report["phase_timings"]["preseed_seconds"] >= 0
    assert (log_dir / "example.insights.json").is_file()
    assert len(validation_calls) == 1


@pytest.mark.asyncio
async def test_force_removes_stale_change_record_for_opt_in_run(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    output_file = architecture.component_output_path(tmp_path, "rhoai.next", "example")
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text("old")
    generation_dir = architecture.component_generation_dir(
        tmp_path, "rhoai.next", "example"
    )
    generation_dir.mkdir(parents=True, exist_ok=True)
    change_file = generation_dir / architecture.CHANGE_RECORD_FILENAME
    change_file.write_text("stale")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", "old")
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=True,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        return [{"name": "example", "success": False, "duration_seconds": 0}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=True,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(tmp_path / "logs"),
        strace=False,
        evidence_gated_merge=True,
    )

    await architecture.run_generate_architecture_phase(args)

    assert not change_file.exists()


@pytest.mark.asyncio
async def test_insufficient_readiness_uses_bounded_partial_route(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Partial agent purpose.")
    write_analyzer_artifacts(
        tmp_path,
        "rhoai.next",
        "example",
        analyzer,
        readiness="insufficient",
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        Path(jobs[0]["output_path"]).write_text(candidate)
        Path(jobs[0]["insight_path"]).write_text(_empty_insight_artifact_json())
        return [{"name": "example", "success": True, "duration_seconds": 2}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    prompt = captured_jobs[0]["prompt"]
    assert "--analysis-route=partial" in prompt
    assert "--change-output" in prompt
    assert "--insights-output" in prompt
    output_text = architecture.component_output_path(
        tmp_path, "rhoai.next", "example"
    ).read_text()
    assert "| api | Service | API |" in output_text
    assert "| api | Library | API |" in (
        log_dir / "example.candidate.md"
    ).read_text()
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["routing"]["readiness"] == "insufficient"
    assert run_report["routing"]["route"] == "partial"
    assert run_report["merge"] is not None
    assert run_report["insights"]["insight_count"] == 0


# ── Insight artifact integration ──


def _synthesis_scaffold(tmp_path, monkeypatch, *, insight_json=None):
    """Set up a synthesis-route run and return (checkout, log_dir, run coroutine).

    *insight_json* controls what the fake agent writes as the insight artifact:
      - string: written as-is to the artifact path
      - None: no artifact written (tests missing-artifact path)
    """
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Agent purpose.")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", analyzer)
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        Path(jobs[0]["output_path"]).write_text(candidate)
        if insight_json is not None:
            Path(jobs[0]["insight_path"]).write_text(insight_json)
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    return checkout, log_dir, architecture.run_generate_architecture_phase(args)


@pytest.mark.asyncio
async def test_valid_insight_artifact_archived_and_reported(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path,
        monkeypatch,
        insight_json=_valid_insight_artifact_json(),
    )
    await coro

    assert (log_dir / "example.insights.json").is_file()
    archived = json.loads((log_dir / "example.insights.json").read_text())
    assert archived["schema_version"] == 1
    assert len(archived["insights"]) == 1

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["insights"]["insight_count"] == 1
    assert run_report["insights"]["artifact_path"] == str(
        log_dir / "example.insights.json"
    )
    assert run_report["insights"]["validation_errors"] == []


def test_cross_component_implication_applicability_archives_without_fallback(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Regression: the observed applicability phrase is repaired before archive."""
    checkout = tmp_path / "example"
    analyzer_root = tmp_path / "example-analyzer"
    generation_dir = tmp_path / "example-generation"
    log_dir = tmp_path / "logs"
    checkout.mkdir()
    analyzer_root.mkdir()
    generation_dir.mkdir()
    log_dir.mkdir()

    analyzer = analyzer_root / "analyzer_architecture.md"
    candidate = tmp_path / "example.md"
    change_path = generation_dir / architecture.CHANGE_RECORD_FILENAME
    insight_path = generation_dir / architecture.INSIGHT_ARTIFACT_FILENAME
    analyzer.write_text(architecture_document("Service", "Analyzer purpose."))
    candidate.write_text(architecture_document("Service", "Analyzer purpose."))
    insight_path.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "component": "example",
                "platform": "rhoai",
                "version": "rhoai.next",
                "insights": [
                    {
                        "id": "cross-001",
                        "claim": "Cross-component observation.",
                        "category": "cross-component implication",
                        "provenance": [
                            {
                                "kind": "analyzer-fact",
                                "location": "Integration Points table",
                            }
                        ],
                        "reasoning": "The effect spans more than one component.",
                        "applicability": "cross-component implication",
                        "confidence": "medium",
                        "validation_status": "pending",
                    }
                ],
            }
        )
    )

    monkeypatch.setattr(
        architecture,
        "merge_architecture_files",
        lambda *a, **kw: SimpleNamespace(
            counts={"applied": 0, "rejected": 0, "restored": 0, "unchanged": 1}
        ),
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    result = {"success": True, "duration_seconds": 1}
    architecture._merge_agent_outputs(
        [
            {
                "name": "example",
                "checkout_path": checkout,
                "analyzer_root": analyzer_root,
                "output_path": candidate,
                "change_path": change_path,
                "insight_path": insight_path,
                "agent_policy": {"route": "partial", "gap_categories": []},
            }
        ],
        [result],
        log_dir,
        platform="rhoai",
        version="rhoai.next",
    )

    assert result["insights"]["insight_count"] == 1
    assert result["insights"]["validation_errors"] == []
    assert "fallback" not in result["insights"]
    assert not (log_dir / "example.insights.invalid.json").exists()

    archived = json.loads((log_dir / "example.insights.json").read_text())
    assert archived["insights"][0]["applicability"] == "cross-component"


@pytest.mark.asyncio
async def test_empty_insight_artifact_is_valid(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path,
        monkeypatch,
        insight_json=_empty_insight_artifact_json(),
    )
    await coro

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["insights"]["insight_count"] == 0
    assert (log_dir / "example.insights.json").is_file()


@pytest.mark.asyncio
async def test_invalid_insight_artifact_does_not_fail_synthesis(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    invalid = json.dumps(
        {
            "schema_version": 1,
            "component": "example",
            "platform": "rhoai",
            "version": "rhoai.next",
            "insights": [{"id": "bad", "category": "opinion"}],
        }
    )
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path, monkeypatch, insight_json=invalid
    )
    await coro

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["error"] is None
    assert run_report["insights"]["error"]
    assert run_report["insights"]["fallback"] == "empty-artifact"
    assert json.loads((log_dir / "example.insights.json").read_text())["insights"] == []
    assert (log_dir / "example.insights.invalid.json").is_file()


@pytest.mark.asyncio
async def test_missing_insight_artifact_does_not_fail_synthesis(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path, monkeypatch, insight_json=None
    )
    await coro

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["error"] is None
    assert "missing insight artifact" in run_report["insights"]["error"]
    assert run_report["insights"]["fallback"] == "empty-artifact"
    fallback = json.loads((log_dir / "example.insights.json").read_text())
    assert fallback["platform"] == "rhoai"
    assert fallback["version"] == "rhoai.next"
    assert fallback["insights"] == []


@pytest.mark.asyncio
async def test_insight_metadata_not_promoted_into_markdown(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path,
        monkeypatch,
        insight_json=_valid_insight_artifact_json(),
    )
    await coro

    markdown = architecture.component_output_path(
        tmp_path, "rhoai.next", "example"
    ).read_text()
    assert "insight" not in markdown.lower() or "insight" not in markdown
    assert "Test pattern." not in markdown
    assert "INSIGHTS_ARTIFACT" not in markdown


# ── Merge/validation fallback tests ──


@pytest.mark.asyncio
async def test_merge_failure_falls_back_to_analyzer_baseline(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", analyzer)
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        Path(jobs[0]["output_path"]).write_text(
            "completely broken markdown that will fail merge"
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    output = architecture.component_output_path(
        tmp_path, "rhoai.next", "example"
    ).read_text()
    assert output.startswith(analyzer.rstrip())
    assert "Analyzer purpose." in output
    assert "| api | Service | API |" in output
    assert "Agent purpose." not in output
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["fallback"] is not None
    assert run_report["fallback"]["route"] == "analyzer-baseline"
    assert run_report["fallback"]["original_route"] == "partial"
    assert run_report["fallback"]["action"] == "analyzer-baseline-restored"
    assert "restricted-route merge failed" in run_report["fallback"]["reason"]
    assert run_report["merge"]["fallback"] == "analyzer-baseline-restored"
    assert run_report["insights"] is None


@pytest.mark.asyncio
async def test_validation_failure_restores_analyzer_baseline_not_legacy(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Validation failure on a restricted route restores the analyzer baseline
    and labels the fallback route as 'analyzer-baseline', not 'legacy'."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Agent purpose.")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", analyzer)
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        Path(jobs[0]["output_path"]).write_text(candidate)
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    call_count = 0

    def fake_validate(command, **kwargs):
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            return SimpleNamespace(
                returncode=1,
                stdout="VALIDATION FAILED: missing required section",
                stderr="",
            )
        return SimpleNamespace(returncode=0, stdout="VALIDATION PASSED", stderr="")

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(architecture.subprocess, "run", fake_validate)

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    output = architecture.component_output_path(
        tmp_path, "rhoai.next", "example"
    ).read_text()
    assert output.startswith(analyzer.rstrip())
    assert "| api | Service | API |" in output
    assert "Agent purpose." not in output
    assert "Analyzer purpose." in output

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["fallback"]["route"] == "analyzer-baseline"
    assert run_report["fallback"]["original_route"] == "partial"
    assert run_report["fallback"]["action"] == "analyzer-baseline-restored"
    assert "validation failed" in run_report["fallback"]["reason"].lower()
    assert run_report["merge"]["fallback"] == "analyzer-baseline-restored"
    assert run_report["insights"] is None


@pytest.mark.asyncio
async def test_historical_synthesis_allowlist_does_not_gate_partial_route(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    from unittest.mock import patch

    import lib.architecture_routing as routing_mod

    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Partial agent purpose.")
    write_analyzer_artifacts(
        tmp_path,
        "rhoai.next",
        "example",
        analyzer,
        analyzer_component="not-on-allowlist",
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        Path(jobs[0]["output_path"]).write_text(candidate)
        Path(jobs[0]["insight_path"]).write_text(_empty_insight_artifact_json())
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )

    with patch.object(
        routing_mod,
        "load_synthesis_migration_allowlist",
        return_value=frozenset({"other-component"}),
    ):
        await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    assert "--analysis-route=partial" in captured_jobs[0]["prompt"]
    assert captured_jobs[0]["agent_policy"]["route"] == "partial"
    assert "valid analyzer baseline" in captured_jobs[0]["agent_policy"]["reason"]
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["routing"]["route"] == "partial"


# ── Partial route prompt contract tests ──


@pytest.mark.asyncio
async def test_partial_prompt_declares_route_contract(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Partial prompt includes route, readiness, gap, and preseeded flags."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", analyzer)
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        Path(jobs[0]["output_path"]).write_text(analyzer)
        Path(jobs[0]["insight_path"]).write_text(_empty_insight_artifact_json())
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    prompt = captured_jobs[0]["prompt"]
    assert "--analysis-route=partial" in prompt
    assert "--readiness=sufficient" in prompt
    assert "--baseline-preseeded" in prompt
    assert "--gap-categories=" in prompt
    assert "--change-output=" in prompt
    assert "--insights-output=" in prompt
    policy = captured_jobs[0]["agent_policy"]
    assert policy["route"] == "partial"
    assert policy["output_preseeded"] is True
    assert policy["discovery_tools"] == ("Glob", "Grep")


@pytest.mark.asyncio
async def test_partial_preseeds_analyzer_baseline_before_agent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """The orchestrator pre-seeds the output from analyzer_architecture.md."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", analyzer)
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    output_before_agent = []

    async def fake_run_agents(jobs, *args, **kwargs):
        output_file = Path(jobs[0]["output_path"])
        if output_file.exists():
            output_before_agent.append(output_file.read_text())
        Path(jobs[0]["insight_path"]).write_text(_empty_insight_artifact_json())
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(output_before_agent) == 1
    assert output_before_agent[0] == analyzer


@pytest.mark.asyncio
async def test_legacy_prompt_excludes_evidence_gated_flags(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Legacy prompt must not include synthesis/partial-specific flags."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        Path(jobs[0]["output_path"]).write_text(
            architecture_document("Library", "Legacy.")
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    prompt = captured_jobs[0]["prompt"]
    assert "--analysis-route=legacy" in prompt
    assert "--baseline-preseeded" not in prompt
    assert "--gap-categories" not in prompt
    assert "--file-budget" not in prompt
    assert "--change-output" not in prompt
    assert "--insights-output" not in prompt


# ── Clean-run isolation tests ──


@pytest.mark.asyncio
async def test_synthesis_overwrites_stale_generated_architecture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Force-regeneration deletes stale platform output and
    the partial route pre-seeds from the fresh analyzer baseline—proving
    stale output from a prior run never seeds synthesis."""
    from unittest.mock import patch

    import lib.architecture_routing as routing_mod

    checkout = tmp_path / "example"
    checkout.mkdir()
    stale_content = "# Stale prior run output\nThis must not survive.\n"
    output_path = architecture.component_output_path(tmp_path, "rhoai.next", "example")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(stale_content)
    analyzer = architecture_document("Service", "Fresh analyzer purpose.")
    write_analyzer_artifacts(tmp_path, "rhoai.next", "example", analyzer)
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=True,
        architecturally_significant=True,
        tier="core_platform",
    )
    output_seen_by_agent = []

    async def fake_run_agents(jobs, *args, **kwargs):
        content = Path(jobs[0]["output_path"]).read_text()
        output_seen_by_agent.append(content)
        Path(jobs[0]["insight_path"]).write_text(_empty_insight_artifact_json())
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=True,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )

    with patch.object(
        routing_mod,
        "load_synthesis_migration_allowlist",
        return_value=frozenset(),
    ):
        await architecture.run_generate_architecture_phase(args)

    assert len(output_seen_by_agent) == 1
    assert output_seen_by_agent[0] == analyzer
    assert "Stale prior run output" not in output_seen_by_agent[0]


@pytest.mark.asyncio
async def test_architecture_output_dir_docs_never_read_during_generation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Prior documents under the architecture/ output directory must not be
    read or staged during generation. The phase only reads component-map.json.

    We verify this structurally: the generation prompt references only the
    checkout path and never mentions the architecture output directory contents.
    Prior .md documents in architecture/ are never part of the agent job data."""
    checkout = tmp_path / "checkout-example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")

    arch_dir = tmp_path / "architecture" / "rhoai.next"
    arch_dir.mkdir(parents=True)
    write_analyzer_artifacts(
        tmp_path / "architecture", "rhoai.next", "example", analyzer
    )
    prior_doc = arch_dir / "other-component.md"
    prior_doc.write_text("# Prior architecture document\nMust not be used.\n")

    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        Path(jobs[0]["output_path"]).write_text(analyzer)
        Path(jobs[0]["insight_path"]).write_text(_empty_insight_artifact_json())
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path / "architecture"),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    prompt = captured_jobs[0]["prompt"]
    assert str(checkout.resolve()) in prompt
    assert "Prior architecture" not in prompt
    assert str(prior_doc) not in prompt
    assert captured_jobs[0]["checkout_path"] == checkout
    assert captured_jobs[0]["cwd"] == "."


@pytest.mark.asyncio
async def test_missing_analyzer_output_falls_back_to_legacy_not_prior_docs(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """When analyzer outputs (component-architecture.json, analyzer_architecture.md)
    are absent, routing falls back to legacy—never to prior architecture documents."""
    checkout = tmp_path / "example"
    checkout.mkdir()

    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        Path(jobs[0]["output_path"]).write_text(
            architecture_document("Service", "Legacy generated.")
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    policy = captured_jobs[0]["agent_policy"]
    assert policy["route"] == "legacy"
    assert policy["readiness"] == "unknown"
    assert "--analysis-route=legacy" in captured_jobs[0]["prompt"]
    assert "--baseline-preseeded" not in captured_jobs[0]["prompt"]
