# ruff: noqa: E501
import importlib.util
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VALIDATOR_PATH = (
    PROJECT_ROOT
    / ".claude/skills/aggregate-platform-architecture/scripts/validate_platform.py"
)
SPEC = importlib.util.spec_from_file_location("validate_platform", VALIDATOR_PATH)
assert SPEC is not None and SPEC.loader is not None
VALIDATOR = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(VALIDATOR)

MINIMAL_PLATFORM_MD = """\
# Platform: RHOAI next

## Metadata

- **Distribution**: RHOAI
- **Version**: next
- **Components Analyzed**: 1
- **Generated By**: test

## Platform Overview

Overview text.

## Component Relationships

### Dependency Graph

```
operator
```

### Central Components

None.

### Integration Patterns

| Pattern | Components Using | Description |
|---------|------------------|-------------|

## Platform Network Architecture

### Namespaces

| Namespace | Purpose | Components |
|-----------|---------|------------|

### Internal Service Mesh

| Setting | Value | Components Using |
|---------|-------|------------------|

## Platform Security

### Authentication Mechanisms

| Pattern | Components Using | Enforcement Point |
|---------|------------------|-------------------|

### Container Security

| Pattern | Components Using | Description |
|---------|------------------|-------------|

## Data Flows

### Key Platform Workflows

None identified.

## Deployment Architecture

### Deployment Topology

Flat.

### Resource Summary

One operator.

### Deployment Manifest Patterns

#### Kustomize Patterns

| Pattern | Components Using | Description |
|---------|------------------|-------------|

#### Distribution Variants

| Component | ODH Path | RHOAI Path | Key Differences |
|-----------|----------|------------|-----------------|

#### Manifest Consumption Pipeline

Direct apply.

### High Availability

| Component | Replicas | HA Mechanism |
|-----------|----------|--------------|

### Disconnected Support

None.

### Multi-Architecture Support

| Architecture | Support Level | Notes |
|--------------|---------------|-------|

## Platform Maturity

Minimal.

## Platform Architectural Analysis

None.

### Serving Path Evolution

| Path | Evidence Components | Entry/Routing Surface | Runtime or Provider Role | Source |
|------|---------------------|-----------------------|--------------------------|--------|
"""

WEBHOOK_SECTION = """\

## Platform Admission Webhooks

### Webhook Ownership

| Component | Mutating | Validating | Conversion | Failure Policy |
|-----------|----------|------------|------------|----------------|
| operator  | 1        | 0          | 0          | Fail           |

### Cross-Component Targets

| Source Component | Webhook | Target Component | Intercepted Types | Type | Failure Policy |
|------------------|---------|------------------|--------------------|------|----------------|

### Cross-Cutting Concerns

| Concern | Components | Affected Resources | Pattern |
|---------|------------|--------------------|---------|

### Overlay Deployment

All webhooks active in default overlay.

"""


def test_validator_passes_without_webhook_section(tmp_path: Path):
    path = tmp_path / "PLATFORM.md"
    path.write_text(MINIMAL_PLATFORM_MD)

    errors, warnings = VALIDATOR.validate(str(path))

    assert not errors


def test_validator_passes_with_webhook_section(tmp_path: Path):
    before_data_flows = "## Data Flows"
    text = MINIMAL_PLATFORM_MD.replace(
        before_data_flows,
        WEBHOOK_SECTION + before_data_flows,
    )
    path = tmp_path / "PLATFORM.md"
    path.write_text(text)

    errors, warnings = VALIDATOR.validate(str(path))

    assert not errors


def test_validator_warns_on_missing_webhook_subsections(tmp_path: Path):
    partial_webhook = """\

## Platform Admission Webhooks

### Webhook Ownership

| Component | Mutating | Validating | Conversion | Failure Policy |
|-----------|----------|------------|------------|----------------|
| operator  | 1        | 0          | 0          | Fail           |

"""
    before_data_flows = "## Data Flows"
    text = MINIMAL_PLATFORM_MD.replace(
        before_data_flows,
        partial_webhook + before_data_flows,
    )
    path = tmp_path / "PLATFORM.md"
    path.write_text(text)

    errors, warnings = VALIDATOR.validate(str(path))

    assert not errors
    missing_subsections = [
        w for w in warnings if "Optional subsection missing" in w
    ]
    assert len(missing_subsections) == 3
    expected_missing = {"Cross-Component Targets", "Cross-Cutting Concerns", "Overlay Deployment"}
    for w in missing_subsections:
        assert any(name in w for name in expected_missing)


def test_validator_rejects_webhook_section_in_wrong_order(tmp_path: Path):
    after_deployment = "## Platform Maturity"
    text = MINIMAL_PLATFORM_MD.replace(
        after_deployment,
        WEBHOOK_SECTION + after_deployment,
    )
    path = tmp_path / "PLATFORM.md"
    path.write_text(text)

    errors, _warnings = VALIDATOR.validate(str(path))

    assert any("out of order" in e.lower() for e in errors)
