import json
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from lib.agent_runner import _AgentExecutionGuard
from lib.phases import architecture
from lib.phases.static_analysis import analyzer_output_dir


def _valid_component_document() -> str:
    return """# Component: Example

## Metadata
- **Repository**: example/example
- **Version**: abc123
- **Distribution**: rhoai
- **Languages**: Python
- **Deployment Type**: Service
- **Generated By**: Test

## Purpose
Example purpose.

## Architectural Analysis
Example analysis.

## Architecture Components
| Component | Type | Purpose |
|-----------|------|---------|
| api | Service | API |

## APIs Exposed
### Custom Resource Definitions (CRDs)
| Group | Version | Kind | Scope | Purpose |
|-------|---------|------|-------|---------|
### HTTP Endpoints
| Path | Method | Port | Protocol | Encryption | Auth | Purpose |
|------|--------|------|----------|------------|------|---------|
### gRPC Services
| Service | Port | Protocol | Encryption | Auth | Purpose |
|---------|------|----------|------------|------|---------|

## Dependencies
### External Dependencies
| Component | Version | Required | Purpose |
|-----------|---------|----------|---------|
### Internal Platform Dependencies
| Component | Interaction Type | Purpose |
|-----------|------------------|---------|

## Network Architecture
### Services
| Service Name | Type | Port | Target Port | Protocol | Encryption | Auth | Exposure |
|--------------|------|------|-------------|----------|------------|------|----------|
### Ingress
| Name | Type | Hosts | Port | Protocol | Encryption | TLS Mode | Exposure |
|------|------|-------|------|----------|------------|----------|----------|
### Egress
| Destination | Port | Protocol | Encryption | Auth | Purpose |
|-------------|------|----------|------------|------|---------|

## Security
### RBAC - Cluster Roles
| Role Name | API Group | Resources | Verbs |
|-----------|-----------|-----------|-------|
### RBAC - Role Bindings
| Binding Name | Namespace | Role | Service Account |
|--------------|-----------|------|-----------------|
### Secrets
| Secret Name | Type | Purpose | Provisioned By | Auto-Rotate |
|-------------|------|---------|----------------|-------------|
### Authentication & Authorization
| Endpoint | Methods | Auth Mechanism | Enforcement Point | Policy |
|----------|---------|----------------|-------------------|--------|

## Data Flows
Example flow.

## Integration Points
| Component | Interaction Type | Port | Protocol | Encryption | Purpose |
|-----------|------------------|------|----------|------------|---------|

## Recent Changes
| Version | Date | Changes |
|---------|------|---------|
"""


@pytest.mark.asyncio
async def test_generation_uses_architecture_outputs_and_checkout_sources(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
):
    checkout = tmp_path / "checkout"
    checkout.mkdir()
    analyzer_root = tmp_path / "architecture" / "rhoai.next" / "example" / ".analyzer"
    analyzer_root.mkdir(parents=True)
    (analyzer_root / "component-architecture.json").write_text(
        json.dumps({"data_coverage": {"agent_baseline": "sufficient: facts"}})
    )
    (analyzer_root / "analyzer_architecture.md").write_text("# analyzer\n")
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured.extend(jobs)
        output_path = Path(jobs[0]["output_path"])
        output_path.write_text(_valid_component_document())
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(architecture, "get_model_display_name", lambda model: "Test")
    monkeypatch.chdir(tmp_path)

    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path / "architecture"),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(tmp_path / "logs"),
        strace=False,
        evidence_gated_merge=False,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(captured) == 1
    job = captured[0]
    assert job["cwd"] == "."
    assert job["checkout_path"] == checkout
    assert job["analyzer_root"] == analyzer_output_dir(
        tmp_path / "architecture", "rhoai.next", "example",
    )
    final_output = (
        tmp_path / "architecture" / "rhoai.next" / "example.md"
    ).resolve()
    candidate_output = (
        tmp_path
        / "architecture"
        / "rhoai.next"
        / "example"
        / ".generation"
        / "candidate.md"
    ).resolve()
    assert job["output_path"] == candidate_output
    assert job["candidate_path"] == candidate_output
    assert job["final_output_path"] == final_output
    assert f"--analyzer-dir={job['analyzer_root']}" in job["prompt"]
    assert f"--output={job['output_path']}" in job["prompt"]
    assert f"--read-justifications-output={job['justification_path']}" in job["prompt"]
    assert job["justification_path"] in job["output_paths"]
    assert job["output_path"].is_file()
    assert final_output.is_file()
    assert "# Component: Example" in final_output.read_text()
    assert not (checkout / "GENERATED_ARCHITECTURE.md").exists()


@pytest.mark.asyncio
async def test_guard_allows_analyzer_reads_and_canonical_output_writes(
    tmp_path: Path,
):
    checkout = tmp_path / "checkout"
    analyzer_root = tmp_path / "architecture" / "example" / ".analyzer"
    output = tmp_path / "architecture" / "example.md"
    checkout.mkdir()
    analyzer_root.mkdir(parents=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    guard = _AgentExecutionGuard(
        {"route": "partial", "readiness": "partial"},
        checkout,
        analyzer_root=analyzer_root,
        output_paths=(output,),
    )

    read_result = await guard.pre_tool_use(
        {"tool_name": "Read", "tool_input": {
            "file_path": str(analyzer_root / "analyzer_architecture.md"),
        }},
        None,
        {},
    )
    write_result = await guard.pre_tool_use(
        {"tool_name": "Write", "tool_input": {
            "file_path": str(output), "content": "# generated\n",
        }},
        None,
        {},
    )
    output_read_result = await guard.pre_tool_use(
        {"tool_name": "Read", "tool_input": {"file_path": str(output)}},
        None,
        {},
    )

    assert read_result == {}
    assert write_result == {}
    assert output_read_result == {}


@pytest.mark.asyncio
async def test_direct_output_mode_blocks_checkout_writes_for_legacy_route(
    tmp_path: Path,
):
    checkout = tmp_path / "checkout"
    output = tmp_path / "architecture" / "example.md"
    checkout.mkdir()
    output.parent.mkdir(parents=True)
    guard = _AgentExecutionGuard(
        {"route": "legacy", "readiness": "legacy"},
        checkout,
        output_paths=(output,),
    )

    result = await guard.pre_tool_use(
        {"tool_name": "Write", "tool_input": {
            "file_path": str(checkout / "GENERATED_ARCHITECTURE.md"),
            "content": "# wrong location\n",
        }},
        None,
        {},
    )

    assert result["hookSpecificOutput"]["permissionDecision"] == "deny"
