import json
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from lib.phases import architecture  # noqa: E402


def _valid_insight_artifact_json(component: str = "example") -> str:
    return json.dumps(
        {
            "schema_version": 1,
            "component": component,
            "platform": "rhoai",
            "version": "rhoai.next",
            "insights": [
                {
                    "id": "test-001",
                    "claim": "Test pattern.",
                    "category": "pattern",
                    "provenance": [
                        {
                            "kind": "analyzer-fact",
                            "location": "Architecture Components table",
                        }
                    ],
                    "reasoning": "Test reasoning.",
                    "applicability": "component",
                    "confidence": "high",
                    "validation_status": "pending",
                }
            ],
        }
    )


def _empty_insight_artifact_json(component: str = "example") -> str:
    return json.dumps(
        {
            "schema_version": 1,
            "component": component,
            "platform": "rhoai",
            "version": "rhoai.next",
            "insights": [],
        }
    )


def architecture_document(component_type: str, purpose: str) -> str:
    return f"""# Component: Example

## Metadata
- **Repository**: example/example
- **Version**: abc123
- **Distribution**: rhoai
- **Languages**: Python
- **Deployment Type**: Service
- **Generated By**: Test Model

## Purpose
{purpose}

## Architecture Components
| Component | Type | Purpose |
|-----------|------|---------|
| api | {component_type} | API |

## Data Flows
Agent data flow.

## Architectural Analysis
Agent analysis.
"""


def analyzer_only_document() -> str:
    return architecture_document("Service", "Analyzer purpose.") + """
## Dependencies

### Internal Platform Dependencies

| Component | Interaction Type | Purpose |
|-----------|------------------|---------|
| platform-api | HTTP client | Platform integration |

## Security

### Authentication & Authorization

| Endpoint | Methods | Auth Mechanism | Enforcement Point | Policy |
|----------|---------|----------------|-------------------|--------|
| /api | GET | Bearer token | middleware | authenticated |

## Integration Points

| Component | Interaction Type | Port | Protocol | Encryption | Purpose |
|-----------|------------------|------|----------|------------|---------|
| database | SQL client | 5432 | PostgreSQL | TLS | persistence |
"""


@pytest.mark.asyncio
async def test_generation_opt_in_archives_merges_reports_and_validates(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Agent purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "sufficient: test analyzer facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        assert (checkout / "GENERATED_ARCHITECTURE.md").read_text() == analyzer
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(candidate)
        (checkout / architecture.INSIGHT_ARTIFACT_FILENAME).write_text(
            _empty_insight_artifact_json()
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    validation_calls = []

    def fake_validate(command, **kwargs):
        validation_calls.append(command)
        return SimpleNamespace(returncode=0, stdout="VALIDATION PASSED", stderr="")

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(architecture.subprocess, "run", fake_validate)

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert "--change-output=ARCHITECTURE_CHANGES.md" in captured_jobs[0]["prompt"]
    assert "--insights-output=INSIGHTS_ARTIFACT.json" in captured_jobs[0]["prompt"]
    assert "--readiness=sufficient" in captured_jobs[0]["prompt"]
    assert "--baseline-preseeded" in captured_jobs[0]["prompt"]
    assert captured_jobs[0]["agent_policy"]["route"] == "synthesis"
    assert (
        "| api | Service | API |"
        in (checkout / "GENERATED_ARCHITECTURE.md").read_text()
    )
    assert "Agent purpose." in (checkout / "GENERATED_ARCHITECTURE.md").read_text()
    assert "| api | Library | API |" in (log_dir / "example.candidate.md").read_text()
    report = json.loads((log_dir / "example.merge.json").read_text())
    assert report["counts"]["restored"] == 1
    assert (log_dir / "example.merge.md").is_file()
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["routing"]["readiness"] == "sufficient"
    assert run_report["merge"]["counts"]["restored"] == 1
    assert run_report["insights"]["insight_count"] == 0
    assert run_report["insights"]["artifact_path"] == str(
        log_dir / "example.insights.json"
    )
    assert (log_dir / "example.insights.json").is_file()
    assert len(validation_calls) == 1


@pytest.mark.asyncio
async def test_analyzer_only_route_skips_agent_and_persists_run_report(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = analyzer_only_document()
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "component": "agents-operator",
                "data_coverage": {
                    "agent_baseline": "sufficient: populated analyzer facts",
                    "source": "partial: dynamic expressions unresolved",
                    "platform_semantics": "partial: aliases unresolved",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fail_if_agents_run(*args, **kwargs):
        raise AssertionError("analyzer-only route must not invoke an agent")

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fail_if_agents_run)
    monkeypatch.setattr(
        architecture,
        "get_model_display_name",
        lambda model: "Test Model",
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *args, **kwargs: SimpleNamespace(
            returncode=0,
            stdout="VALIDATION PASSED",
            stderr="",
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )

    await architecture.run_generate_architecture_phase(args)

    output = (checkout / "GENERATED_ARCHITECTURE.md").read_text()
    assert analyzer in output
    report = json.loads((log_dir / "example.run.json").read_text())
    assert report["success"] is True
    assert report["routing"]["route"] == "analyzer-only"
    assert report["telemetry"] == {}
    assert report["merge"] is None
    assert not (log_dir / "example.merge.json").exists()


@pytest.mark.asyncio
async def test_force_removes_stale_change_record_for_opt_in_run(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    (checkout / "GENERATED_ARCHITECTURE.md").write_text("old")
    change_file = checkout / architecture.CHANGE_RECORD_FILENAME
    change_file.write_text("stale")
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=True,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        return [{"name": "example", "success": False, "duration_seconds": 0}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=True,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(tmp_path / "logs"),
        strace=False,
        evidence_gated_merge=True,
    )

    await architecture.run_generate_architecture_phase(args)

    assert not change_file.exists()


@pytest.mark.asyncio
async def test_insufficient_readiness_retains_legacy_full_document_path(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Legacy agent purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "insufficient: no runtime facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(candidate)
        return [{"name": "example", "success": True, "duration_seconds": 2}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    prompt = captured_jobs[0]["prompt"]
    assert "--analysis-route=legacy" in prompt
    assert "--change-output" not in prompt
    assert "--insights-output" not in prompt
    assert (
        "| api | Library | API |"
        in (checkout / "GENERATED_ARCHITECTURE.md").read_text()
    )
    assert not (log_dir / "example.merge.json").exists()
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["routing"]["readiness"] == "insufficient"
    assert run_report["merge"] is None
    assert run_report["insights"] is None


# ── Insight artifact integration ──


def _synthesis_scaffold(tmp_path, monkeypatch, *, insight_json=None):
    """Set up a synthesis-route run and return (checkout, log_dir, run coroutine).

    *insight_json* controls what the fake agent writes as the insight artifact:
      - string: written as-is to the artifact path
      - None: no artifact written (tests missing-artifact path)
    """
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Agent purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "sufficient: test analyzer facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(candidate)
        if insight_json is not None:
            (checkout / architecture.INSIGHT_ARTIFACT_FILENAME).write_text(
                insight_json
            )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    return checkout, log_dir, architecture.run_generate_architecture_phase(args)


@pytest.mark.asyncio
async def test_valid_insight_artifact_archived_and_reported(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path,
        monkeypatch,
        insight_json=_valid_insight_artifact_json(),
    )
    await coro

    assert (log_dir / "example.insights.json").is_file()
    archived = json.loads((log_dir / "example.insights.json").read_text())
    assert archived["schema_version"] == 1
    assert len(archived["insights"]) == 1

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["insights"]["insight_count"] == 1
    assert run_report["insights"]["artifact_path"] == str(
        log_dir / "example.insights.json"
    )
    assert run_report["insights"]["validation_errors"] == []


@pytest.mark.asyncio
async def test_empty_insight_artifact_is_valid(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path,
        monkeypatch,
        insight_json=_empty_insight_artifact_json(),
    )
    await coro

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["insights"]["insight_count"] == 0
    assert (log_dir / "example.insights.json").is_file()


@pytest.mark.asyncio
async def test_invalid_insight_artifact_fails_synthesis(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    invalid = json.dumps(
        {
            "schema_version": 1,
            "component": "example",
            "platform": "rhoai",
            "version": "rhoai.next",
            "insights": [{"id": "bad", "category": "opinion"}],
        }
    )
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path, monkeypatch, insight_json=invalid
    )
    await coro

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is False
    assert "insight artifact failed" in run_report["error"]
    assert run_report["insights"]["error"]


@pytest.mark.asyncio
async def test_missing_insight_artifact_fails_synthesis(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _, log_dir, coro = _synthesis_scaffold(
        tmp_path, monkeypatch, insight_json=None
    )
    await coro

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is False
    assert "insight artifact failed" in run_report["error"]
    assert "missing insight artifact" in run_report["insights"]["error"]


@pytest.mark.asyncio
async def test_insight_metadata_not_promoted_into_markdown(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    checkout, log_dir, coro = _synthesis_scaffold(
        tmp_path,
        monkeypatch,
        insight_json=_valid_insight_artifact_json(),
    )
    await coro

    markdown = (checkout / "GENERATED_ARCHITECTURE.md").read_text()
    assert "insight" not in markdown.lower() or "insight" not in markdown
    assert "Test pattern." not in markdown
    assert "INSIGHTS_ARTIFACT" not in markdown


@pytest.mark.asyncio
async def test_analyzer_only_route_has_no_insights_in_report(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    """Analyzer-only runs produce no insight artifact or metadata."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = analyzer_only_document()
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "component": "agents-operator",
                "data_coverage": {
                    "agent_baseline": "sufficient: populated analyzer facts",
                    "source": "partial: dynamic expressions unresolved",
                    "platform_semantics": "partial: aliases unresolved",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fail_if_agents_run(*args, **kwargs):
        raise AssertionError("analyzer-only route must not invoke an agent")

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fail_if_agents_run)
    monkeypatch.setattr(
        architecture,
        "get_model_display_name",
        lambda model: "Test Model",
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *args, **kwargs: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr="",
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )

    await architecture.run_generate_architecture_phase(args)

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["routing"]["route"] == "analyzer-only"
    assert run_report["insights"] is None
    assert not (log_dir / "example.insights.json").exists()


# ── Merge/validation fallback tests ──


@pytest.mark.asyncio
async def test_merge_failure_falls_back_to_analyzer_baseline(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "sufficient: test analyzer facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(
            "completely broken markdown that will fail merge"
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    output = (checkout / "GENERATED_ARCHITECTURE.md").read_text()
    assert output.startswith(analyzer.rstrip())
    assert "Analyzer purpose." in output
    assert "| api | Service | API |" in output
    assert "Agent purpose." not in output
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["fallback"] is not None
    assert run_report["fallback"]["route"] == "analyzer-baseline"
    assert run_report["fallback"]["original_route"] == "synthesis"
    assert run_report["fallback"]["action"] == "analyzer-baseline-restored"
    assert "restricted-route merge failed" in run_report["fallback"]["reason"]
    assert run_report["merge"]["fallback"] == "analyzer-baseline-restored"
    assert run_report["insights"] is None


@pytest.mark.asyncio
async def test_validation_failure_restores_analyzer_baseline_not_legacy(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Validation failure on a restricted route restores the analyzer baseline
    and labels the fallback route as 'analyzer-baseline', not 'legacy'."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Agent purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "sufficient: test analyzer facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )

    async def fake_run_agents(jobs, *args, **kwargs):
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(candidate)
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    call_count = 0

    def fake_validate(command, **kwargs):
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            return SimpleNamespace(
                returncode=1,
                stdout="VALIDATION FAILED: missing required section",
                stderr="",
            )
        return SimpleNamespace(returncode=0, stdout="VALIDATION PASSED", stderr="")

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(architecture.subprocess, "run", fake_validate)

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    output = (checkout / "GENERATED_ARCHITECTURE.md").read_text()
    assert output.startswith(analyzer.rstrip())
    assert "| api | Service | API |" in output
    assert "Agent purpose." not in output
    assert "Analyzer purpose." in output

    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["success"] is True
    assert run_report["fallback"]["route"] == "analyzer-baseline"
    assert run_report["fallback"]["original_route"] == "synthesis"
    assert run_report["fallback"]["action"] == "analyzer-baseline-restored"
    assert "validation failed" in run_report["fallback"]["reason"].lower()
    assert run_report["merge"]["fallback"] == "analyzer-baseline-restored"
    assert run_report["insights"] is None


@pytest.mark.asyncio
async def test_synthesis_allowlist_gates_route_in_phase(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    from unittest.mock import patch

    import lib.architecture_routing as routing_mod

    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    candidate = architecture_document("Library", "Legacy agent purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "component": "not-on-allowlist",
                "data_coverage": {
                    "agent_baseline": "sufficient: test analyzer facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(candidate)
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )

    with patch.object(
        routing_mod,
        "load_synthesis_migration_allowlist",
        return_value=frozenset({"other-component"}),
    ):
        await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    assert "--analysis-route=legacy" in captured_jobs[0]["prompt"]
    assert captured_jobs[0]["agent_policy"]["route"] == "legacy"
    assert "synthesis migration allowlist" in captured_jobs[0]["agent_policy"]["reason"]
    run_report = json.loads((log_dir / "example.run.json").read_text())
    assert run_report["routing"]["route"] == "legacy"


# ── Synthesis route prompt contract tests ──


@pytest.mark.asyncio
async def test_synthesis_prompt_declares_route_contract(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Synthesis prompt includes route, readiness, gap, and preseeded flags."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "sufficient: test analyzer facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(analyzer)
        (checkout / architecture.INSIGHT_ARTIFACT_FILENAME).write_text(
            _empty_insight_artifact_json()
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    prompt = captured_jobs[0]["prompt"]
    assert "--analysis-route=synthesis" in prompt
    assert "--readiness=sufficient" in prompt
    assert "--baseline-preseeded" in prompt
    assert "--gap-categories=" in prompt
    assert "--change-output=ARCHITECTURE_CHANGES.md" in prompt
    assert "--insights-output=INSIGHTS_ARTIFACT.json" in prompt
    policy = captured_jobs[0]["agent_policy"]
    assert policy["route"] == "synthesis"
    assert policy["output_preseeded"] is True
    assert policy["discovery_tools"] == ()


@pytest.mark.asyncio
async def test_synthesis_preseeds_analyzer_baseline_before_agent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """The orchestrator pre-seeds the output from ANALYZER_ARCHITECTURE.md."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    analyzer = architecture_document("Service", "Analyzer purpose.")
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(analyzer)
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "sufficient: test analyzer facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    output_before_agent = []

    async def fake_run_agents(jobs, *args, **kwargs):
        output_file = checkout / "GENERATED_ARCHITECTURE.md"
        if output_file.exists():
            output_before_agent.append(output_file.read_text())
        (checkout / architecture.INSIGHT_ARTIFACT_FILENAME).write_text(
            _empty_insight_artifact_json()
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )
    monkeypatch.setattr(
        architecture.subprocess,
        "run",
        lambda *a, **kw: SimpleNamespace(
            returncode=0, stdout="VALIDATION PASSED", stderr=""
        ),
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(output_before_agent) == 1
    assert output_before_agent[0] == analyzer


@pytest.mark.asyncio
async def test_legacy_prompt_excludes_evidence_gated_flags(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """Legacy prompt must not include synthesis/partial-specific flags."""
    checkout = tmp_path / "example"
    checkout.mkdir()
    (checkout / "ANALYZER_ARCHITECTURE.md").write_text(
        architecture_document("Service", "Analyzer purpose.")
    )
    (checkout / "component-architecture.json").write_text(
        json.dumps(
            {
                "data_coverage": {
                    "agent_baseline": "insufficient: no runtime facts",
                }
            }
        )
    )
    component = SimpleNamespace(
        key="example",
        repo_org="example-org",
        repo_name="example-repo",
        checkout_path=checkout,
        has_architecture=False,
        architecturally_significant=True,
        tier="core_platform",
    )
    captured_jobs = []

    async def fake_run_agents(jobs, *args, **kwargs):
        captured_jobs.extend(jobs)
        (checkout / "GENERATED_ARCHITECTURE.md").write_text(
            architecture_document("Library", "Legacy.")
        )
        return [{"name": "example", "success": True, "duration_seconds": 1}]

    monkeypatch.setattr(
        architecture,
        "read_component_map",
        lambda *args, **kwargs: {"example": component},
    )
    monkeypatch.setattr(architecture, "load_platform_config", lambda *args: {})
    monkeypatch.setattr(architecture, "run_agents_concurrently", fake_run_agents)
    monkeypatch.setattr(
        architecture, "get_model_display_name", lambda model: "Test Model"
    )

    log_dir = tmp_path / "logs"
    args = SimpleNamespace(
        platform="rhoai.next",
        architecture_dir=str(tmp_path),
        component=None,
        tier="all",
        force=False,
        limit=None,
        model="opus",
        max_concurrent=1,
        log_dir=str(log_dir),
        strace=False,
        evidence_gated_merge=True,
    )
    await architecture.run_generate_architecture_phase(args)

    assert len(captured_jobs) == 1
    prompt = captured_jobs[0]["prompt"]
    assert "--analysis-route=legacy" in prompt
    assert "--baseline-preseeded" not in prompt
    assert "--gap-categories" not in prompt
    assert "--file-budget" not in prompt
    assert "--change-output" not in prompt
    assert "--insights-output" not in prompt
