import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.rebase_architecture_synthesis import (  # noqa: E402
    rebase_synthesis,
    split_h2_sections,
)


def test_rebase_changes_only_agent_owned_sections_and_metadata():
    analyzer = """# Component: Example

## Metadata

- **Generated By**: arch-analyzer

## Purpose

Pending.

## Architecture Components

| Component | Type | Purpose |
|-----------|------|---------|
| api | service | API |

## Data Flows

Pending.

## Architectural Analysis

Pending.

## Recent Changes

| Version | Date | Changes |
|---------|------|---------|
"""
    synthesis = analyzer.replace("Pending.", "Agent synthesis.")

    result = rebase_synthesis(analyzer, synthesis, generated_by="Test Agent")

    assert "- **Generated By**: Test Agent" in result
    assert result.count("Agent synthesis.") == 3
    _, before, _ = split_h2_sections(analyzer)
    _, after, _ = split_h2_sections(result)
    for name in ("Architecture Components", "Recent Changes"):
        assert after[name] == before[name]
