"""Evidence-gated merge of agent synthesis onto analyzer Markdown."""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Literal

from lib.architecture_baseline import (
    _TABLE_SPECS,
    MarkdownTable,
    _normalize_header,
    _normalize_key_value,
    _normalize_row_key,
    _normalize_section,
    _normalize_text,
    parse_component_markdown_text,
)

SYNTHESIS_SECTIONS = ("Purpose", "Data Flows", "Architectural Analysis")
CONDITIONAL_H2_SECTIONS = (
    "AIPCC Ecosystems Use",
    "Sub-Component Details",
    "Deployment Manifests",
)
CONDITIONAL_H3_SECTIONS = {
    "Security": ("FIPS Compliance", "Build Hermeticity"),
}
CHANGE_RECORD_HEADERS = (
    "Action",
    "Category",
    "Row Key",
    "Column",
    "Analyzer Value",
    "Candidate Value",
    "Reason",
    "Evidence",
)
EMPTY_VALUE = "<empty>"
NON_FACT_KEY_VALUES = frozenset(
    {
        "none identified",
        "no dependencies identified",
        "no internal dependencies identified",
        "not applicable",
    }
)
CORRECTION_ADJUDICATIONS_PATH = (
    Path(__file__).resolve().parent / "analyzer_correction_adjudications.json"
)

_H2_RE = re.compile(r"(?m)^## ([^\n]+)\n")
_H3_RE = re.compile(r"(?m)^### ([^\n]+)\n")
_GENERATED_BY_RE = re.compile(r"(?m)^- \*\*Generated By\*\*:.*$")
_TOTAL_FILES_RE = re.compile(r"(?m)^- \*\*Total files referenced\*\*:.*$")
_EVIDENCE_RE = re.compile(r"(?:^|[\s,;])([^\s,:;]+):(\d+)(?:-(\d+))?(?=$|[\s,;])")

DecisionStatus = Literal["applied", "rejected", "restored"]


@dataclass(frozen=True)
class ChangeRecord:
    """One exact agent-requested structured fact change."""

    action: Literal["add", "update", "delete"]
    category: str
    key: tuple[str, ...]
    column: str
    analyzer_value: str
    candidate_value: str
    reason: str
    evidence: tuple[str, ...]
    source_row: int

    @property
    def identity(self) -> tuple[str, str, tuple[str, ...], str]:
        return self.action, self.category, self.key, self.column


@dataclass(frozen=True)
class MergeDecision:
    """An applied, rejected, or automatically restored candidate change."""

    status: DecisionStatus
    action: str
    category: str
    key: tuple[str, ...]
    column: str = "*"
    analyzer_value: str = ""
    candidate_value: str = ""
    reason: str = ""
    evidence: tuple[str, ...] = ()
    detail: str = ""


@dataclass
class MergeResult:
    """Merged document plus an auditable account of every observed change."""

    text: str
    decisions: list[MergeDecision] = field(default_factory=list)
    unchanged_by_category: dict[str, int] = field(default_factory=dict)
    parse_errors: list[str] = field(default_factory=list)
    component: str = ""

    @property
    def counts(self) -> dict[str, int]:
        counts = Counter(decision.status for decision in self.decisions)
        counts["unchanged"] = sum(self.unchanged_by_category.values())
        return {
            status: counts.get(status, 0)
            for status in ("unchanged", "applied", "rejected", "restored")
        }

    @property
    def accepted_conflicts(self) -> list[dict[str, object]]:
        """Return corpus-comparator adjudications for applied cell updates."""

        conflicts = [
            {
                "category": decision.category,
                "key": list(decision.key),
                "column": decision.column,
                "analyzer": decision.analyzer_value,
                "generated": decision.candidate_value,
                "reason": decision.reason,
                "evidence": list(decision.evidence),
            }
            for decision in self.decisions
            if decision.status == "applied" and decision.action == "update"
        ]
        if self.component:
            for conflict in conflicts:
                conflict["component"] = self.component
        return conflicts

    @property
    def accepted_deletions(self) -> list[dict[str, object]]:
        """Return corpus-comparator adjudications for applied row deletions."""

        deletions = [
            {
                "category": decision.category,
                "key": list(decision.key),
                "reason": decision.reason,
                "evidence": list(decision.evidence),
            }
            for decision in self.decisions
            if decision.status == "applied" and decision.action == "delete"
        ]
        if self.component:
            for deletion in deletions:
                deletion["component"] = self.component
        return deletions

    def to_dict(self) -> dict[str, object]:
        return {
            "schema_version": 1,
            "counts": self.counts,
            "unchanged_by_category": self.unchanged_by_category,
            "parse_errors": self.parse_errors,
            "decisions": [asdict(decision) for decision in self.decisions],
            "accepted_conflicts": self.accepted_conflicts,
            "accepted_deletions": self.accepted_deletions,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2) + "\n"

    def to_markdown(self, *, component: str = "component") -> str:
        lines = [
            f"# Architecture Merge Report: {component}",
            "",
            "## Summary",
            "",
            "| Status | Count |",
            "|--------|------:|",
        ]
        lines.extend(
            f"| {status.title()} | {count} |" for status, count in self.counts.items()
        )
        lines.extend(
            [
                "",
                "## Unchanged Analyzer Rows",
                "",
                "| Category | Rows |",
                "|----------|-----:|",
            ]
        )
        if self.unchanged_by_category:
            lines.extend(
                f"| {_escape_cell(category)} | {count} |"
                for category, count in sorted(self.unchanged_by_category.items())
            )
        else:
            lines.append("| None | 0 |")

        if self.parse_errors:
            lines.extend(["", "## Change Record Errors", ""])
            lines.extend(f"- {_escape_cell(error)}" for error in self.parse_errors)

        for status in ("applied", "rejected", "restored"):
            decisions = [item for item in self.decisions if item.status == status]
            lines.extend(
                [
                    "",
                    f"## {status.title()} Changes",
                    "",
                    (
                        "| Action | Category | Row Key | Column | Analyzer | "
                        "Candidate | Evidence | Detail |"
                    ),
                    (
                        "|--------|----------|---------|--------|----------|"
                        "-----------|----------|--------|"
                    ),
                ]
            )
            if not decisions:
                lines.append("| - | - | - | - | - | - | - | None |")
                continue
            for decision in decisions:
                lines.append(
                    "| "
                    + " | ".join(
                        _escape_cell(value)
                        for value in (
                            decision.action,
                            decision.category,
                            " :: ".join(decision.key),
                            decision.column,
                            _display_value(decision.analyzer_value),
                            _display_value(decision.candidate_value),
                            "; ".join(decision.evidence),
                            decision.detail or decision.reason,
                        )
                    )
                    + " |"
                )
        return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class _Row:
    category: str
    key: tuple[str, ...]
    raw: tuple[str, ...]
    headers: tuple[str, ...]

    @property
    def cells(self) -> dict[str, str]:
        return {
            _normalize_header(header): self.raw[index]
            for index, header in enumerate(self.headers)
            if index < len(self.raw)
        }


@dataclass
class _TableRows:
    table: MarkdownTable
    category: str
    rows: list[_Row]


def split_h2_sections(text: str) -> tuple[str, dict[str, str], list[str]]:
    """Split a Markdown document into its preamble and complete H2 blocks."""

    matches = list(_H2_RE.finditer(text))
    if not matches:
        return text, {}, []
    preamble = text[: matches[0].start()]
    sections: dict[str, str] = {}
    order: list[str] = []
    for index, match in enumerate(matches):
        name = match.group(1).strip()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        sections[name] = text[match.start() : end]
        order.append(name)
    return preamble, sections, order


def rebase_synthesis(
    analyzer_text: str,
    synthesis_text: str,
    *,
    generated_by: str,
) -> str:
    """Retain the original synthesis-only rebase as a supported operation."""

    preamble, analyzer_sections, order = split_h2_sections(analyzer_text)
    _, synthesis_sections, _ = split_h2_sections(synthesis_text)
    missing = [name for name in SYNTHESIS_SECTIONS if name not in synthesis_sections]
    if missing:
        raise ValueError("synthesis document missing sections: " + ", ".join(missing))
    for name in SYNTHESIS_SECTIONS:
        if name not in analyzer_sections:
            raise ValueError(f"analyzer document missing section: {name}")
        analyzer_sections[name] = synthesis_sections[name]
    result = preamble + "".join(analyzer_sections[name] for name in order)
    return _replace_generated_by(result, generated_by)


def parse_change_records(text: str) -> tuple[list[ChangeRecord], list[str]]:
    """Parse the agent-facing Markdown structured-change table."""

    document = parse_component_markdown_text(text, path="<change-record>")
    table = next(
        (
            item
            for item in document.tables
            if tuple(_normalize_header(header) for header in item.headers)
            == tuple(_normalize_header(header) for header in CHANGE_RECORD_HEADERS)
        ),
        None,
    )
    if table is None:
        return [], [
            "missing change table with headers: " + ", ".join(CHANGE_RECORD_HEADERS)
        ]

    records: list[ChangeRecord] = []
    errors: list[str] = []
    specs = {spec.category: spec for spec in _TABLE_SPECS}
    for offset, raw in enumerate(table.rows, start=table.start_line + 2):
        values = dict(zip(CHANGE_RECORD_HEADERS, raw, strict=False))
        action = _normalize_text(values.get("Action", ""))
        category = _normalize_header(values.get("Category", ""))
        column = _normalize_header(values.get("Column", "")) or "*"
        reason = values.get("Reason", "").strip()
        analyzer_value = _decode_value(values.get("Analyzer Value", ""))
        candidate_value = _decode_value(values.get("Candidate Value", ""))
        # Agents commonly format source references as inline Markdown code. The
        # backticks are presentation syntax, not part of the repository path.
        evidence_text = _expand_evidence_shorthand(
            values.get("Evidence", "").replace("`", "").strip()
        )
        evidence = tuple(
            match.group(0).strip(" ,;")
            for match in _EVIDENCE_RE.finditer(evidence_text)
        )
        row_errors = []
        if action not in {"add", "update", "delete"}:
            row_errors.append(f"unsupported action {action!r}")
        spec = specs.get(category)
        if spec is None:
            row_errors.append(f"unsupported category {category!r}")
        raw_key = tuple(
            part.strip()
            for part in re.split(r"\s+::\s+", values.get("Row Key", "").strip())
            if part.strip()
        )
        key = raw_key
        if spec is not None:
            if len(raw_key) < len(spec.keys):
                row_errors.append(
                    f"row key needs at least {len(spec.keys)} value(s), "
                    f"got {len(raw_key)}"
                )
            else:
                # Agents sometimes append displayed non-key cells, such as
                # ``Component :: Interaction Type``. The leading key cells are
                # authoritative and sufficient to identify the candidate row.
                raw_key = raw_key[: len(spec.keys)]
                key = tuple(
                    _normalize_key_value(category, key_column, value)
                    for key_column, value in zip(spec.keys, raw_key, strict=True)
                )
                if any(value in NON_FACT_KEY_VALUES for value in key):
                    row_errors.append(
                        "row key must identify a concrete architecture fact"
                    )
        if action in {"add", "delete"} and column != "*":
            row_errors.append(f"{action} requires Column '*' ")
        if action in {"add", "delete"} and (analyzer_value or candidate_value):
            row_errors.append(
                f"{action} requires Analyzer Value and Candidate Value '<empty>'"
            )
        if action == "update" and column == "*":
            row_errors.append("update requires a concrete column")
        if not reason or _normalize_text(reason) in {"-", "none", "n/a"}:
            row_errors.append("reason is required")
        if not evidence:
            row_errors.append("numeric file:line evidence is required")
        for reference in evidence:
            match = _EVIDENCE_RE.fullmatch(reference)
            if match is None:
                continue
            evidence_path = Path(match.group(1))
            if evidence_path.is_absolute() or ".." in evidence_path.parts:
                row_errors.append(
                    f"evidence path must be repository-relative: {match.group(1)!r}"
                )
            if match.group(3) and int(match.group(3)) < int(match.group(2)):
                row_errors.append(f"evidence range is reversed: {reference!r}")
        unmatched_evidence = _EVIDENCE_RE.sub("", evidence_text).strip(" ,;")
        if evidence_text and unmatched_evidence:
            row_errors.append(f"invalid evidence syntax {unmatched_evidence!r}")
        if row_errors:
            errors.extend(f"change table row {offset}: {error}" for error in row_errors)
            continue
        records.append(
            ChangeRecord(
                action=action,  # type: ignore[arg-type]
                category=category,
                key=key,
                column=column,
                analyzer_value=analyzer_value,
                candidate_value=candidate_value,
                reason=reason,
                evidence=evidence,
                source_row=offset,
            )
        )
    return records, errors


def _expand_evidence_shorthand(evidence_text: str) -> str:
    """Expand ``path:10-20,25`` into two complete evidence references."""

    references: list[str] = []
    current_path: str | None = None
    for raw_reference in re.split(r"([,;])", evidence_text):
        reference = raw_reference.strip()
        if not reference or reference in {",", ";"}:
            continue
        match = _EVIDENCE_RE.fullmatch(reference)
        if match is not None:
            current_path = match.group(1)
            references.append(reference)
            continue
        if current_path and re.fullmatch(r"\d+(?:-\d+)?", reference):
            references.append(f"{current_path}:{reference}")
            continue
        references.append(reference)
    return ", ".join(references)


def merge_architecture_documents(
    analyzer_text: str,
    candidate_text: str,
    *,
    changes_text: str | None = None,
    generated_by: str | None = None,
    component: str = "",
    allowed_change_categories: tuple[str, ...] | None = None,
    rejected_additions: dict[
        tuple[str, tuple[str, ...]], tuple[str, tuple[str, ...]]
    ]
    | None = None,
) -> MergeResult:
    """Merge candidate synthesis and evidence-backed facts onto analyzer Markdown."""

    analyzer_document = parse_component_markdown_text(analyzer_text, path="<analyzer>")
    candidate_document = parse_component_markdown_text(
        candidate_text, path="<candidate>"
    )
    records, parse_errors = (
        parse_change_records(changes_text) if changes_text is not None else ([], [])
    )
    if allowed_change_categories is not None:
        allowed = set(allowed_change_categories)
        disallowed = [record for record in records if record.category not in allowed]
        records = [record for record in records if record.category in allowed]
        parse_errors.extend(
            (
                f"change table row {record.source_row}: category {record.category!r} "
                "is outside the readiness gap budget"
            )
            for record in disallowed
        )
    records_by_identity: dict[
        tuple[str, str, tuple[str, ...], str], list[ChangeRecord]
    ] = defaultdict(list)
    for record in records:
        records_by_identity[record.identity].append(record)

    analyzer_tables = _document_table_rows(analyzer_document.tables)
    candidate_tables = _document_table_rows(candidate_document.tables)
    candidate_by_category = _rows_by_category(candidate_tables)
    candidate_row_groups = _row_groups_by_category(candidate_tables)
    decisions: list[MergeDecision] = []
    unchanged: Counter[str] = Counter()
    used_records: set[ChangeRecord] = set()
    replacements: list[tuple[int, int, list[str]]] = []

    first_table_by_category: dict[str, _TableRows] = {}
    for item in analyzer_tables:
        first_table_by_category.setdefault(item.category, item)

    analyzer_by_category = _rows_by_category(analyzer_tables)
    for table_rows in analyzer_tables:
        candidate_rows = candidate_by_category.get(table_rows.category, {})
        candidate_groups = candidate_row_groups.get(table_rows.category, {})
        output_rows: list[tuple[str, ...]] = []
        for analyzer_row in table_rows.rows:
            candidates = candidate_groups.get(analyzer_row.key, [])
            exact_index = next(
                (
                    index
                    for index, row in enumerate(candidates)
                    if row.raw == analyzer_row.raw
                ),
                None,
            )
            candidate_row = (
                candidates.pop(exact_index)
                if exact_index is not None
                else candidates.pop(0)
                if candidates
                else None
            )
            if candidate_row is None:
                record = _select_record(
                    records_by_identity,
                    "delete",
                    table_rows.category,
                    analyzer_row.key,
                    "*",
                )
                if record and _row_record_matches(record, analyzer_row, None):
                    used_records.add(record)
                    decisions.append(_decision_from_record("applied", record))
                    continue
                output_rows.append(analyzer_row.raw)
                decisions.append(
                    MergeDecision(
                        status="restored",
                        action="delete",
                        category=table_rows.category,
                        key=analyzer_row.key,
                        analyzer_value=_row_display(analyzer_row),
                        candidate_value="",
                        detail="candidate omitted analyzer row without exact evidence",
                    )
                )
                continue

            if table_rows.category in {"source_files", "source_searches"}:
                merged_raw = _merge_evidence_row(analyzer_row, candidate_row)
                row_decisions = []
                row_unchanged = int(merged_raw == analyzer_row.raw)
                row_records = set()
            else:
                (
                    merged_raw,
                    row_decisions,
                    row_unchanged,
                    row_records,
                ) = _merge_shared_row(
                    analyzer_row,
                    candidate_row,
                    records_by_identity,
                )
            output_rows.append(merged_raw)
            decisions.extend(row_decisions)
            unchanged[table_rows.category] += row_unchanged
            used_records.update(row_records)

        if table_rows is first_table_by_category[table_rows.category]:
            analyzer_rows = analyzer_by_category.get(table_rows.category, {})
            for key, candidate_row in candidate_rows.items():
                if key in analyzer_rows:
                    continue
                if table_rows.category in {"source_files", "source_searches"}:
                    output_rows.append(
                        _translate_row(candidate_row, table_rows.table.headers)
                    )
                    decisions.append(
                        MergeDecision(
                            status="applied",
                            action="add",
                            category=table_rows.category,
                            key=key,
                            candidate_value=_row_display(candidate_row),
                            detail="merged agent source evidence",
                        )
                    )
                    continue
                record = _select_record(
                    records_by_identity,
                    "add",
                    table_rows.category,
                    key,
                    "*",
                )
                adjudication = (
                    (rejected_additions or {}).get(
                        (table_rows.category, key)
                    )
                    if record
                    else None
                )
                if (
                    record
                    and adjudication
                    and _row_record_matches(record, None, candidate_row)
                ):
                    used_records.add(record)
                    reason, evidence = adjudication
                    decisions.append(
                        MergeDecision(
                            status="rejected",
                            action="add",
                            category=table_rows.category,
                            key=key,
                            candidate_value=_row_display(candidate_row),
                            reason=reason,
                            evidence=evidence,
                            detail="source-adjudicated analyzer absence: " + reason,
                        )
                    )
                elif record and _row_record_matches(record, None, candidate_row):
                    used_records.add(record)
                    output_rows.append(
                        _translate_row(candidate_row, table_rows.table.headers)
                    )
                    decisions.append(_decision_from_record("applied", record))
                else:
                    decisions.append(
                        MergeDecision(
                            status="rejected",
                            action="add",
                            category=table_rows.category,
                            key=key,
                            candidate_value=_row_display(candidate_row),
                            detail="candidate-only row has no exact evidence record",
                        )
                    )

        start = table_rows.table.start_line - 1
        end = start + 2 + len(table_rows.table.rows)
        replacements.append(
            (
                start,
                end,
                _render_table(table_rows.table.headers, output_rows),
            )
        )

    for category, candidate_rows in candidate_by_category.items():
        if category in first_table_by_category:
            continue
        for row in candidate_rows.values():
            decisions.append(
                MergeDecision(
                    status="rejected",
                    action="add",
                    category=category,
                    key=row.key,
                    candidate_value=_row_display(row),
                    detail="analyzer document has no destination table for category",
                )
            )

    for record in records:
        if record not in used_records:
            decisions.append(
                MergeDecision(
                    status="rejected",
                    action=record.action,
                    category=record.category,
                    key=record.key,
                    column=record.column,
                    analyzer_value=record.analyzer_value,
                    candidate_value=record.candidate_value,
                    reason=record.reason,
                    evidence=record.evidence,
                    detail=(
                        "stale or mismatched change record from row "
                        f"{record.source_row}"
                    ),
                )
            )

    structured_analyzer = _apply_line_replacements(analyzer_text, replacements)
    text = _merge_owned_sections(structured_analyzer, candidate_text)
    text = _append_applied_evidence_sources(text, decisions)
    if generated_by:
        text = _replace_generated_by(text, generated_by)
    return MergeResult(
        text=text,
        decisions=decisions,
        unchanged_by_category=dict(sorted(unchanged.items())),
        parse_errors=parse_errors,
        component=component,
    )


def merge_architecture_files(
    analyzer: Path,
    candidate: Path,
    output: Path,
    *,
    changes: Path | None = None,
    report_json: Path | None = None,
    report_markdown: Path | None = None,
    generated_by: str | None = None,
    component: str | None = None,
    allowed_change_categories: tuple[str, ...] | None = None,
) -> MergeResult:
    """Merge files and write optional audit artifacts."""

    resolved_component = component or candidate.parent.name
    result = merge_architecture_documents(
        analyzer.read_text(),
        candidate.read_text(),
        changes_text=changes.read_text() if changes and changes.exists() else None,
        generated_by=generated_by,
        component=resolved_component,
        allowed_change_categories=allowed_change_categories,
        rejected_additions=load_rejected_additions(resolved_component),
    )
    output.write_text(result.text)
    if report_json:
        report_json.parent.mkdir(parents=True, exist_ok=True)
        report_json.write_text(result.to_json())
    if report_markdown:
        report_markdown.parent.mkdir(parents=True, exist_ok=True)
        report_markdown.write_text(
            result.to_markdown(component=component or candidate.parent.name)
        )
    return result


def load_rejected_additions(
    component: str,
    path: Path = CORRECTION_ADJUDICATIONS_PATH,
) -> dict[tuple[str, tuple[str, ...]], tuple[str, tuple[str, ...]]]:
    """Load exact source-reviewed agent additions that must not be reapplied."""

    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    result = {}
    for entry in payload.get("accepted_analyzer_absences", []):
        if not isinstance(entry, dict) or entry.get("component") != component:
            continue
        category = str(entry.get("category") or "").strip()
        key = _normalize_row_key(
            category, tuple(str(value) for value in entry.get("key") or ())
        )
        reason = str(entry.get("reason") or "").strip()
        evidence = tuple(str(value) for value in entry.get("evidence") or ())
        if category and key and reason and evidence:
            result[(category, key)] = (reason, evidence)
    return result


def _document_table_rows(tables: list[MarkdownTable]) -> list[_TableRows]:
    result = []
    for table in tables:
        spec = next(
            (
                item
                for item in _TABLE_SPECS
                if _normalize_section(table.section) in item.sections
            ),
            None,
        )
        if spec is None:
            continue
        mapped_headers = [
            spec.aliases.get(_normalize_header(header), "") for header in table.headers
        ]
        rows = []
        for raw in table.rows:
            values = {
                mapped: raw[index]
                for index, mapped in enumerate(mapped_headers)
                if mapped and index < len(raw)
            }
            key = tuple(
                _normalize_key_value(spec.category, column, values.get(column, ""))
                for column in spec.keys
            )
            if all(key) and not any(
                value in NON_FACT_KEY_VALUES for value in key
            ):
                rows.append(_Row(spec.category, key, raw, table.headers))
        result.append(_TableRows(table=table, category=spec.category, rows=rows))
    return result


def _rows_by_category(
    tables: list[_TableRows],
) -> dict[str, dict[tuple[str, ...], _Row]]:
    result: dict[str, dict[tuple[str, ...], _Row]] = defaultdict(dict)
    for table in tables:
        for row in table.rows:
            result[table.category][row.key] = row
    return dict(result)


def _row_groups_by_category(
    tables: list[_TableRows],
) -> dict[str, dict[tuple[str, ...], list[_Row]]]:
    """Retain duplicate row identities so identical occurrences can be paired."""

    result: dict[str, dict[tuple[str, ...], list[_Row]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for table in tables:
        for row in table.rows:
            result[table.category][row.key].append(row)
    return {
        category: dict(rows_by_key) for category, rows_by_key in result.items()
    }


def _merge_shared_row(
    analyzer: _Row,
    candidate: _Row,
    records: dict[tuple[str, str, tuple[str, ...], str], list[ChangeRecord]],
) -> tuple[tuple[str, ...], list[MergeDecision], int, set[ChangeRecord]]:
    output = list(analyzer.raw)
    candidate_cells = candidate.cells
    decisions = []
    used = set()
    for index, header in enumerate(analyzer.headers):
        column = _normalize_header(header)
        if index >= len(output) or column not in candidate_cells:
            continue
        left = output[index].strip()
        right = candidate_cells[column].strip()
        if left == right:
            continue
        record = _select_record(
            records, "update", analyzer.category, analyzer.key, column
        )
        if record and record.analyzer_value == left and record.candidate_value == right:
            output[index] = candidate_cells[column]
            used.add(record)
            decisions.append(_decision_from_record("applied", record))
        else:
            decisions.append(
                MergeDecision(
                    status="restored",
                    action="update",
                    category=analyzer.category,
                    key=analyzer.key,
                    column=column,
                    analyzer_value=left,
                    candidate_value=right,
                    detail="candidate changed analyzer cell without exact evidence",
                )
            )
    merged = tuple(output)
    return merged, decisions, int(merged == analyzer.raw), used


def _merge_evidence_row(analyzer: _Row, candidate: _Row) -> tuple[str, ...]:
    """Union source-reference cells without discarding analyzer evidence."""

    candidate_cells = candidate.cells
    output = list(analyzer.raw)
    key_columns = {_normalize_header(header) for header in analyzer.headers[:1]}
    for index, header in enumerate(analyzer.headers):
        column = _normalize_header(header)
        if column in key_columns or column not in candidate_cells:
            continue
        left = output[index].strip()
        right = candidate_cells[column].strip()
        if not right or right == left:
            continue
        if not left:
            output[index] = right
        else:
            output[index] = f"{left}; {right}"
    return tuple(output)


def _append_applied_evidence_sources(text: str, decisions: list[MergeDecision]) -> str:
    """Ensure every applied change source is present in Files Analyzed."""

    document = parse_component_markdown_text(text, path="<merged>")
    source_table = next(
        (
            item
            for item in document.tables
            if _normalize_section(item.section) == "files analyzed"
        ),
        None,
    )
    if source_table is None:
        return text
    headers = tuple(_normalize_header(header) for header in source_table.headers)
    try:
        file_index = headers.index("file")
        lines_index = headers.index("lines")
        sections_index = headers.index("sections_informed")
    except ValueError:
        return text

    rows = [list(row) for row in source_table.rows]
    by_file = {
        row[file_index].strip(): row
        for row in rows
        if file_index < len(row) and row[file_index].strip()
    }
    for decision in decisions:
        if decision.status != "applied":
            continue
        for evidence in decision.evidence:
            match = _EVIDENCE_RE.fullmatch(evidence)
            if not match:
                continue
            path = match.group(1)
            line_range = match.group(2)
            if match.group(3):
                line_range += f"-{match.group(3)}"
            row = by_file.get(path)
            if row is None:
                row = [""] * len(headers)
                row[file_index] = path
                row[lines_index] = line_range
                row[sections_index] = decision.category
                rows.append(row)
                by_file[path] = row
                continue
            row[lines_index] = _union_list_value(row[lines_index], line_range)
            row[sections_index] = _union_list_value(
                row[sections_index], decision.category
            )

    start = source_table.start_line - 1
    end = start + 2 + len(source_table.rows)
    result = _apply_line_replacements(
        text,
        [
            (
                start,
                end,
                _render_table(source_table.headers, [tuple(row) for row in rows]),
            )
        ],
    )
    return _TOTAL_FILES_RE.sub(
        f"- **Total files referenced**: {len(rows)}", result, count=1
    )


def _union_list_value(left: str, right: str) -> str:
    if not left:
        return right
    items = [item.strip() for item in left.split(";") if item.strip()]
    if right not in items:
        items.append(right)
    return "; ".join(items)


def _select_record(
    records: dict[tuple[str, str, tuple[str, ...], str], list[ChangeRecord]],
    action: str,
    category: str,
    key: tuple[str, ...],
    column: str,
) -> ChangeRecord | None:
    matches = records.get((action, category, key, column), [])
    return matches[0] if len(matches) == 1 else None


def _row_record_matches(
    record: ChangeRecord,
    analyzer: _Row | None,
    candidate: _Row | None,
) -> bool:
    if record.action == "add":
        return candidate is not None and not record.analyzer_value
    if record.action == "delete":
        return analyzer is not None and not record.candidate_value
    return False


def _decision_from_record(
    status: DecisionStatus, record: ChangeRecord
) -> MergeDecision:
    return MergeDecision(
        status=status,
        action=record.action,
        category=record.category,
        key=record.key,
        column=record.column,
        analyzer_value=record.analyzer_value,
        candidate_value=record.candidate_value,
        reason=record.reason,
        evidence=record.evidence,
        detail=record.reason,
    )


def _translate_row(row: _Row, headers: tuple[str, ...]) -> tuple[str, ...]:
    cells = row.cells
    return tuple(cells.get(_normalize_header(header), "") for header in headers)


def _render_table(headers: tuple[str, ...], rows: list[tuple[str, ...]]) -> list[str]:
    return [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("-" * max(3, len(header)) for header in headers) + "|",
        *("| " + " | ".join(row) + " |" for row in rows),
    ]


def _apply_line_replacements(
    text: str, replacements: list[tuple[int, int, list[str]]]
) -> str:
    lines = text.splitlines()
    for start, end, replacement in sorted(replacements, reverse=True):
        lines[start:end] = replacement
    return "\n".join(lines) + "\n"


def _merge_owned_sections(analyzer_text: str, candidate_text: str) -> str:
    preamble, analyzer_sections, analyzer_order = split_h2_sections(analyzer_text)
    _, candidate_sections, candidate_order = split_h2_sections(candidate_text)
    for name in SYNTHESIS_SECTIONS:
        if name not in candidate_sections:
            raise ValueError(f"candidate document missing synthesis section: {name}")
        if name not in analyzer_sections:
            raise ValueError(f"analyzer document missing synthesis section: {name}")
        analyzer_sections[name] = candidate_sections[name]

    security = analyzer_sections.get("Security")
    candidate_security = candidate_sections.get("Security")
    if security and candidate_security:
        for subsection in CONDITIONAL_H3_SECTIONS["Security"]:
            block = _extract_h3(candidate_security, subsection)
            if block and not _extract_h3(security, subsection):
                security = security.rstrip() + "\n\n" + block.rstrip() + "\n\n"
        analyzer_sections["Security"] = security

    output_order = list(analyzer_order)
    for name in CONDITIONAL_H2_SECTIONS:
        if name not in candidate_sections or name in analyzer_sections:
            continue
        analyzer_sections[name] = candidate_sections[name]
        candidate_index = candidate_order.index(name)
        preceding = [
            item for item in candidate_order[:candidate_index] if item in output_order
        ]
        insert_at = output_order.index(preceding[-1]) + 1 if preceding else 0
        output_order.insert(insert_at, name)

    result = preamble + "".join(analyzer_sections[name] for name in output_order)
    candidate_generated_by = _GENERATED_BY_RE.search(candidate_text)
    if candidate_generated_by:
        result, count = _GENERATED_BY_RE.subn(
            candidate_generated_by.group(0), result, count=1
        )
        if count != 1:
            raise ValueError(
                "analyzer document has no unique Generated By metadata row"
            )
    return result


def _extract_h3(section: str, name: str) -> str | None:
    matches = list(_H3_RE.finditer(section))
    for index, match in enumerate(matches):
        if match.group(1).strip() != name:
            continue
        end = matches[index + 1].start() if index + 1 < len(matches) else len(section)
        return section[match.start() : end]
    return None


def _replace_generated_by(text: str, generated_by: str) -> str:
    replacement = f"- **Generated By**: {generated_by}"
    result, count = _GENERATED_BY_RE.subn(replacement, text, count=1)
    if count != 1:
        raise ValueError("analyzer document has no unique Generated By metadata row")
    return result


def _decode_value(value: str) -> str:
    value = value.strip()
    return "" if value == EMPTY_VALUE else value


def _display_value(value: str) -> str:
    return value if value else EMPTY_VALUE


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _row_display(row: _Row) -> str:
    return " | ".join(row.raw)
