#!/usr/bin/env python3
"""Validate a PLATFORM.md file against the canonical template."""

import re
import sys
from pathlib import Path


REQUIRED_H2_SECTIONS = [
    "Metadata",
    "Platform Overview",
    "Component Inventory",
    "Component Relationships",
    "Platform Network Architecture",
    "Platform Security",
    "Platform APIs",
    "Data Flows",
    "Deployment Architecture",
    "Platform Maturity",
]

REQUIRED_H3_SUBSECTIONS = {
    "Component Relationships": [
        "Dependency Graph",
        "Central Components",
        "Integration Patterns",
    ],
    "Platform Network Architecture": [
        "Namespaces",
        "External Ingress Points",
        "External Egress Dependencies",
        "Internal Service Mesh",
    ],
    "Platform Security": [
        "RBAC Summary",
        "Secrets Inventory",
        "Authentication Mechanisms",
    ],
    "Platform APIs": [
        "Custom Resource Definitions",
        "Public HTTP Endpoints",
    ],
    "Data Flows": [
        "Key Platform Workflows",
    ],
    "Deployment Architecture": [
        "Deployment Topology",
        "Resource Summary",
    ],
}

REQUIRED_METADATA_FIELDS = [
    "Distribution",
    "Version",
    "Components Analyzed",
    "Generated By",
]

EXPECTED_TABLE_HEADERS = {
    "Component Inventory": ["Component", "Type", "Version", "Purpose"],
    "Integration Patterns": ["Pattern", "Components Using", "Description"],
    "Namespaces": ["Namespace", "Purpose", "Components"],
    "External Ingress Points": [
        "Component", "Ingress Type", "Hosts", "Port", "Protocol", "Encryption", "Purpose",
    ],
    "External Egress Dependencies": [
        "Component", "Destination", "Port", "Protocol", "Encryption", "Purpose",
    ],
    "Internal Service Mesh": ["Setting", "Value", "Components Using"],
    "RBAC Summary": ["Component", "ClusterRole", "Key Resources", "Key Verbs"],
    "Secrets Inventory": ["Component", "Secret Name", "Type", "Purpose"],
    "Authentication Mechanisms": ["Pattern", "Components Using", "Enforcement Point"],
    "Custom Resource Definitions": ["Component", "API Group", "Kind", "Scope", "Purpose"],
    "Public HTTP Endpoints": [
        "Component", "Path", "Method", "Port", "Protocol", "Auth", "Purpose",
    ],
    "Version-Specific Changes": ["Component", "Changes"],
}


def _parse_headings(text: str) -> list[tuple[int, str]]:
    """Extract (level, title) for all markdown headings."""
    headings = []
    for line in text.splitlines():
        m = re.match(r'^(#{1,6})\s+(.+)$', line)
        if m:
            headings.append((len(m.group(1)), m.group(2).strip()))
    return headings


def _parse_tables(text: str) -> dict[str, list[str]]:
    """Map section heading -> table column headers found under it."""
    tables: dict[str, list[str]] = {}
    current_section = None

    for line in text.splitlines():
        m = re.match(r'^(#{2,3})\s+(.+)$', line)
        if m:
            current_section = m.group(2).strip()
            # Strip "Workflow N:" prefix for data flow sub-workflows
            current_section = re.sub(r'^Workflow \d+:\s*', '', current_section)
            # Strip numbered prefix (e.g., "1. Platform Overview")
            current_section = re.sub(r'^\d+\.\s*', '', current_section)
            # Strip version suffix from "Version-Specific Changes (X.Y)"
            current_section = re.sub(r'\s*\(.+\)$', '', current_section)
            continue

        if current_section and current_section not in tables:
            if line.strip().startswith('|') and '---' not in line:
                cols = [c.strip() for c in line.strip().strip('|').split('|')]
                cols = [c for c in cols if c]
                if cols:
                    tables[current_section] = cols

    return tables


def _parse_metadata_fields(text: str) -> list[str]:
    """Extract metadata field names from the Metadata section."""
    fields = []
    in_metadata = False
    for line in text.splitlines():
        if re.match(r'^##\s+Metadata\s*$', line):
            in_metadata = True
            continue
        if in_metadata and re.match(r'^##\s+', line):
            break
        if in_metadata:
            m = re.match(r'^-\s+\*\*(.+?)\*\*:', line)
            if m:
                fields.append(m.group(1))
            # Also support table-format metadata (| **Field** | Value |)
            m2 = re.match(r'^\|\s*\*\*(.+?)\*\*\s*\|', line)
            if m2:
                fields.append(m2.group(1))
    return fields


def validate(path: str) -> tuple[list[str], list[str]]:
    """Return (errors, warnings). Errors are blocking, warnings are informational."""
    errors = []
    warnings = []
    filepath = Path(path)

    if not filepath.exists():
        return [f"File not found: {path}"], []

    text = filepath.read_text()

    if not text.strip():
        return ["File is empty"], []

    headings = _parse_headings(text)

    # --- H1 check ---
    h1s = [title for level, title in headings if level == 1]
    if not h1s:
        errors.append("Missing H1 heading (expected '# Platform: [Name] [Version]')")
    elif not h1s[0].startswith("Platform:"):
        warnings.append(f"H1 should start with 'Platform:' (got '# {h1s[0]}')")

    # --- H2 section presence and order ---
    # Normalize: strip numbered prefixes and known suffixes
    raw_h2s = [title for level, title in headings if level == 2]
    h2s = []
    for title in raw_h2s:
        normalized = re.sub(r'^\d+\.\s*', '', title)
        normalized = re.sub(r'\s*\(.+\)$', '', normalized)
        h2s.append(normalized)

    # "Version-Specific Changes" is optional but expected
    all_expected = REQUIRED_H2_SECTIONS + ["Version-Specific Changes"]
    found_required = [s for s in h2s if s in all_expected]
    missing_h2 = [s for s in REQUIRED_H2_SECTIONS if s not in h2s]

    for section in missing_h2:
        errors.append(f"Missing required section: ## {section}")

    # Check order of found sections
    expected_order = [s for s in all_expected if s in found_required]
    if found_required != expected_order:
        errors.append(
            f"Sections out of order. Expected: {expected_order}, "
            f"got: {found_required}"
        )

    # Warn on extra H2 sections
    extra_h2 = [s for s in h2s if s not in all_expected]
    for section in extra_h2:
        warnings.append(f"Unexpected section: ## {section} (not in template)")

    # --- H3 subsections ---
    h3_by_parent: dict[str, list[str]] = {}
    current_h2 = None
    for level, title in headings:
        if level == 2:
            normalized = re.sub(r'^\d+\.\s*', '', title)
            normalized = re.sub(r'\s*\(.+\)$', '', normalized)
            current_h2 = normalized
        elif level == 3 and current_h2:
            h3_by_parent.setdefault(current_h2, []).append(title)

    for h2, required_h3s in REQUIRED_H3_SUBSECTIONS.items():
        if h2 in missing_h2:
            continue
        actual_h3s = h3_by_parent.get(h2, [])
        for h3 in required_h3s:
            if h3 not in actual_h3s:
                errors.append(f"Missing subsection: ### {h3} (under ## {h2})")

    # --- Metadata fields ---
    if "Metadata" not in missing_h2:
        meta_fields = _parse_metadata_fields(text)
        for field in REQUIRED_METADATA_FIELDS:
            if field not in meta_fields:
                errors.append(f"Missing metadata field: **{field}**")

    # --- Table column headers ---
    tables = _parse_tables(text)
    for section_name, expected_cols in EXPECTED_TABLE_HEADERS.items():
        if section_name in tables:
            actual_cols = tables[section_name]
            if actual_cols != expected_cols:
                warnings.append(
                    f"Table columns mismatch in '{section_name}': "
                    f"expected {expected_cols}, got {actual_cols}"
                )

    return errors, warnings


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <PLATFORM.md>")
        sys.exit(2)

    errors, warnings = validate(sys.argv[1])

    if warnings:
        print(f"WARNINGS ({len(warnings)}):\n")
        for w in warnings:
            print(f"  ~ {w}")
        print()

    if errors:
        print(f"VALIDATION FAILED - {len(errors)} error(s):\n")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)
    else:
        print("VALIDATION PASSED")
        sys.exit(0)


if __name__ == "__main__":
    main()
