package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const testDocument = `# Component: Example

## Metadata

- **Generated By**: analyzer

## Purpose

analyzer purpose

## Architectural Analysis

analyzer analysis

## Architecture Components

| Component | Type | Purpose |
|---|---|---|

## APIs Exposed

## Dependencies

## Network Architecture

## Security

## Data Flows

analyzer flows

## Integration Points

## Recent Changes
`

func TestParseAndValidateDocument(t *testing.T) {
	doc := parseDocument(testDocument)
	if issues := validateDocument(doc); len(issues) != 0 {
		t.Fatalf("unexpected validation issues: %v", issues)
	}
	if got := ownerFor("Architecture Components"); got != "analyzer" {
		t.Fatalf("owner = %q, want analyzer", got)
	}
	if got := ownerFor("Architectural Analysis"); got != "synthesis" {
		t.Fatalf("owner = %q, want synthesis", got)
	}
}

func TestManifestOwnershipClassesDoNotOverlap(t *testing.T) {
	classes := map[string][]string{
		"analyzer":              config.AnalyzerSections,
		"synthesis":             config.SynthesisSections,
		"conditional synthesis": config.ConditionalSynthesis,
		"shared":                config.SharedSections,
		"non-authoritative":     config.NonAuthoritativeSections,
	}
	owners := map[string]string{}
	for class, names := range classes {
		for _, name := range names {
			if previous, exists := owners[name]; exists {
				t.Fatalf("section %q is both %s and %s", name, previous, class)
			}
			owners[name] = class
		}
	}
	if got := ownerFor("Deployment Manifests"); got != "synthesis-conditional" {
		t.Fatalf("Deployment Manifests owner = %q, want synthesis-conditional", got)
	}
}

func TestAssemblePreservesAnalyzerSectionsAndUsesSynthesisSections(t *testing.T) {
	base := parseDocument(testDocument)
	candidate := parseDocument(strings.ReplaceAll(strings.ReplaceAll(testDocument,
		"analyzer purpose", "agent purpose"),
		"analyzer analysis", "agent analysis"))
	candidate = parseDocument(strings.ReplaceAll(renderDocument(candidate), "analyzer flows", "agent flows"))
	assembled, err := assembleDocuments(base, candidate)
	if err != nil {
		t.Fatal(err)
	}
	result := renderDocument(assembled)
	if !strings.Contains(result, "agent purpose") || !strings.Contains(result, "agent analysis") || !strings.Contains(result, "agent flows") {
		t.Fatalf("synthesis sections were not replaced:\n%s", result)
	}
	if !strings.Contains(result, "## Architecture Components") || !strings.Contains(result, "## APIs Exposed") {
		t.Fatalf("analyzer sections were not preserved:\n%s", result)
	}
	assembledSections := parseDocument(result)
	baseSections := sectionMap(base.Sections)
	for _, name := range []string{
		"Metadata", "Architecture Components", "APIs Exposed", "Dependencies",
		"Network Architecture", "Security", "Integration Points", "Recent Changes",
	} {
		if sectionMap(assembledSections.Sections)[name].Text != baseSections[name].Text {
			t.Fatalf("analyzer section %q changed during assembly", name)
		}
	}
	if !strings.Contains(result, "- **Generated By**: analyzer") {
		t.Fatalf("base metadata should remain when candidate has no metadata override")
	}
}

func TestUpdateRejectsAnalyzerOwnedSection(t *testing.T) {
	path := filepath.Join(t.TempDir(), "doc.md")
	if err := os.WriteFile(path, []byte(testDocument), 0o644); err != nil {
		t.Fatal(err)
	}
	content := filepath.Join(t.TempDir(), "content.md")
	if err := os.WriteFile(content, []byte("changed"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := runUpdate([]string{path, "--section", "Metadata", "--input", content}); err == nil {
		t.Fatal("expected analyzer-owned update to fail")
	}
}

func TestUpdateReplacesOnlySynthesisSection(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "doc.md")
	content := filepath.Join(dir, "purpose.md")
	if err := os.WriteFile(path, []byte(testDocument), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(content, []byte("new purpose"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := runUpdate([]string{path, "--section", "Purpose", "--input", content}); err != nil {
		t.Fatal(err)
	}
	updated, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(updated), "new purpose") || !strings.Contains(string(updated), "analyzer analysis") {
		t.Fatalf("unexpected update result:\n%s", updated)
	}
}

func TestUpdateRejectsIncompleteDocumentBeforeWriting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "doc.md")
	content := filepath.Join(dir, "purpose.md")
	incomplete := strings.Replace(testDocument, "## Dependencies\n", "", 1)
	if err := os.WriteFile(path, []byte(incomplete), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(content, []byte("new purpose"), 0o644); err != nil {
		t.Fatal(err)
	}

	err := runUpdate([]string{path, "--section", "Purpose", "--input", content})
	if err == nil || !strings.Contains(err.Error(), "missing required section: Dependencies") {
		t.Fatalf("expected incomplete document rejection, got %v", err)
	}
	updated, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if strings.Contains(string(updated), "new purpose") {
		t.Fatal("update changed document after validation failure")
	}
}

func TestUpdateRejectsInjectedUnknownSectionBeforeWriting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "doc.md")
	content := filepath.Join(dir, "purpose.md")
	if err := os.WriteFile(path, []byte(testDocument), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(content, []byte("new purpose\n\n## Invented Section\n\ninvalid"), 0o644); err != nil {
		t.Fatal(err)
	}

	err := runUpdate([]string{path, "--section", "Purpose", "--input", content})
	if err == nil || !strings.Contains(err.Error(), "unknown section: Invented Section") {
		t.Fatalf("expected injected section rejection, got %v", err)
	}
	updated, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if strings.Contains(string(updated), "new purpose") {
		t.Fatal("update changed document after marker validation failure")
	}
}

func TestDuplicateSectionsFailValidation(t *testing.T) {
	doc := parseDocument(testDocument + "\n## Purpose\n\nduplicate\n")
	issues := validateDocument(doc)
	if len(issues) == 0 || !strings.Contains(strings.Join(issues, ";"), "duplicate section: Purpose") {
		t.Fatalf("expected duplicate section validation, got %v", issues)
	}
}

func TestUnknownSectionsFailValidation(t *testing.T) {
	doc := parseDocument(testDocument + "\n## Invented Section\n\ncontent\n")
	issues := validateDocument(doc)
	if len(issues) == 0 || !strings.Contains(strings.Join(issues, ";"), "unknown section: Invented Section") {
		t.Fatalf("expected unknown section validation, got %v", issues)
	}
}

func TestAssemblePreservesMissingSecuritySynthesisSubsection(t *testing.T) {
	base := parseDocument(testDocument)
	candidate := parseDocument(testDocument)
	security := sectionMap(candidate.Sections)["Security"]
	security.Text += "\n### FIPS Compliance\n\nFIPS evidence\n"
	candidate, _ = replaceSection(candidate, "Security", security.Text, false)
	assembled, err := assembleDocuments(base, candidate)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(sectionMap(assembled.Sections)["Security"].Text, "FIPS evidence") {
		t.Fatal("expected candidate FIPS subsection to be carried into Security")
	}
}

func TestAssembleRejectsIncompleteBaseBeforeWriting(t *testing.T) {
	dir := t.TempDir()
	basePath := filepath.Join(dir, "base.md")
	candidatePath := filepath.Join(dir, "candidate.md")
	outputPath := filepath.Join(dir, "assembled.md")

	base := parseDocument(testDocument)
	filtered := make([]section, 0, len(base.Sections)-1)
	for _, item := range base.Sections {
		if item.Name != "Dependencies" {
			filtered = append(filtered, item)
		}
	}
	base.Sections = filtered
	if err := os.WriteFile(basePath, []byte(renderDocument(base)), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(candidatePath, []byte(testDocument), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := runAssemble([]string{
		"--base", basePath,
		"--candidate", candidatePath,
		"--output", outputPath,
	}); err == nil || !strings.Contains(err.Error(), "missing required section: Dependencies") {
		t.Fatalf("expected incomplete base rejection, got %v", err)
	}
	if _, err := os.Stat(outputPath); !os.IsNotExist(err) {
		t.Fatalf("assemble created output after validation failure: %v", err)
	}
}
